-- Generated by lampe

import std.Extracted.GeneratedTypes
import Lampe

open Lampe

set_option linter.unusedVariables false

noir_type_alias «Multiple-0.0.0»::baz::asdf::Asdf<> := Field;

noir_struct_def «Multiple-0.0.0»::bar::Asdf2<> {
  @«Multiple-0.0.0»::baz::asdf::Asdf<>,
}

noir_type_alias «Multiple-0.0.0»::Asdf3<> := «Multiple-0.0.0»::bar::Asdf2<>;

