-- Generated by lampe

import «GitDepWithLampe-0.0.0».Extracted.GeneratedTypes
import «GitDepWithLampe-0.0.0».Extracted.Lib
import std.Extracted

namespace «GitDepWithLampe-0.0.0»

def env := Lib.env
  ++ std.env
