-- Generated by lampe

import std.Extracted.GeneratedTypes
import Lampe

open Lampe

set_option linter.unusedVariables false

noir_trait_impl[std.impl_116]<> std::ops::arith::Add<> for Field where [] := {
  noir_def add<>(self: Field, other: Field) -> Field := {
    (#_fAdd returning Field)(self, other)
  };
}

noir_trait_impl[std.impl_117]<> std::ops::arith::Add<> for u128 where [] := {
  noir_def add<>(self: u128, other: u128) -> u128 := {
    (#_uAdd returning u128)(self, other)
  };
}

noir_trait_impl[std.impl_118]<> std::ops::arith::Add<> for u64 where [] := {
  noir_def add<>(self: u64, other: u64) -> u64 := {
    (#_uAdd returning u64)(self, other)
  };
}

noir_trait_impl[std.impl_119]<> std::ops::arith::Add<> for u32 where [] := {
  noir_def add<>(self: u32, other: u32) -> u32 := {
    (#_uAdd returning u32)(self, other)
  };
}

noir_trait_impl[std.impl_120]<> std::ops::arith::Add<> for u16 where [] := {
  noir_def add<>(self: u16, other: u16) -> u16 := {
    (#_uAdd returning u16)(self, other)
  };
}

noir_trait_impl[std.impl_121]<> std::ops::arith::Add<> for u8 where [] := {
  noir_def add<>(self: u8, other: u8) -> u8 := {
    (#_uAdd returning u8)(self, other)
  };
}

noir_trait_impl[std.impl_122]<> std::ops::arith::Add<> for u1 where [] := {
  noir_def add<>(self: u1, other: u1) -> u1 := {
    (#_uAdd returning u1)(self, other)
  };
}

noir_trait_impl[std.impl_123]<> std::ops::arith::Add<> for i8 where [] := {
  noir_def add<>(self: i8, other: i8) -> i8 := {
    (#_iAdd returning i8)(self, other)
  };
}

noir_trait_impl[std.impl_124]<> std::ops::arith::Add<> for i16 where [] := {
  noir_def add<>(self: i16, other: i16) -> i16 := {
    (#_iAdd returning i16)(self, other)
  };
}

noir_trait_impl[std.impl_125]<> std::ops::arith::Add<> for i32 where [] := {
  noir_def add<>(self: i32, other: i32) -> i32 := {
    (#_iAdd returning i32)(self, other)
  };
}

noir_trait_impl[std.impl_126]<> std::ops::arith::Add<> for i64 where [] := {
  noir_def add<>(self: i64, other: i64) -> i64 := {
    (#_iAdd returning i64)(self, other)
  };
}

noir_trait_impl[std.impl_127]<> std::ops::arith::Sub<> for Field where [] := {
  noir_def sub<>(self: Field, other: Field) -> Field := {
    (#_fSub returning Field)(self, other)
  };
}

noir_trait_impl[std.impl_128]<> std::ops::arith::Sub<> for u128 where [] := {
  noir_def sub<>(self: u128, other: u128) -> u128 := {
    (#_uSub returning u128)(self, other)
  };
}

noir_trait_impl[std.impl_129]<> std::ops::arith::Sub<> for u64 where [] := {
  noir_def sub<>(self: u64, other: u64) -> u64 := {
    (#_uSub returning u64)(self, other)
  };
}

noir_trait_impl[std.impl_130]<> std::ops::arith::Sub<> for u32 where [] := {
  noir_def sub<>(self: u32, other: u32) -> u32 := {
    (#_uSub returning u32)(self, other)
  };
}

noir_trait_impl[std.impl_131]<> std::ops::arith::Sub<> for u16 where [] := {
  noir_def sub<>(self: u16, other: u16) -> u16 := {
    (#_uSub returning u16)(self, other)
  };
}

noir_trait_impl[std.impl_132]<> std::ops::arith::Sub<> for u8 where [] := {
  noir_def sub<>(self: u8, other: u8) -> u8 := {
    (#_uSub returning u8)(self, other)
  };
}

noir_trait_impl[std.impl_133]<> std::ops::arith::Sub<> for u1 where [] := {
  noir_def sub<>(self: u1, other: u1) -> u1 := {
    (#_uSub returning u1)(self, other)
  };
}

noir_trait_impl[std.impl_134]<> std::ops::arith::Sub<> for i8 where [] := {
  noir_def sub<>(self: i8, other: i8) -> i8 := {
    (#_iSub returning i8)(self, other)
  };
}

noir_trait_impl[std.impl_135]<> std::ops::arith::Sub<> for i16 where [] := {
  noir_def sub<>(self: i16, other: i16) -> i16 := {
    (#_iSub returning i16)(self, other)
  };
}

noir_trait_impl[std.impl_136]<> std::ops::arith::Sub<> for i32 where [] := {
  noir_def sub<>(self: i32, other: i32) -> i32 := {
    (#_iSub returning i32)(self, other)
  };
}

noir_trait_impl[std.impl_137]<> std::ops::arith::Sub<> for i64 where [] := {
  noir_def sub<>(self: i64, other: i64) -> i64 := {
    (#_iSub returning i64)(self, other)
  };
}

noir_trait_impl[std.impl_138]<> std::ops::arith::Mul<> for Field where [] := {
  noir_def mul<>(self: Field, other: Field) -> Field := {
    (#_fMul returning Field)(self, other)
  };
}

noir_trait_impl[std.impl_139]<> std::ops::arith::Mul<> for u128 where [] := {
  noir_def mul<>(self: u128, other: u128) -> u128 := {
    (#_uMul returning u128)(self, other)
  };
}

noir_trait_impl[std.impl_140]<> std::ops::arith::Mul<> for u64 where [] := {
  noir_def mul<>(self: u64, other: u64) -> u64 := {
    (#_uMul returning u64)(self, other)
  };
}

noir_trait_impl[std.impl_141]<> std::ops::arith::Mul<> for u32 where [] := {
  noir_def mul<>(self: u32, other: u32) -> u32 := {
    (#_uMul returning u32)(self, other)
  };
}

noir_trait_impl[std.impl_142]<> std::ops::arith::Mul<> for u16 where [] := {
  noir_def mul<>(self: u16, other: u16) -> u16 := {
    (#_uMul returning u16)(self, other)
  };
}

noir_trait_impl[std.impl_143]<> std::ops::arith::Mul<> for u8 where [] := {
  noir_def mul<>(self: u8, other: u8) -> u8 := {
    (#_uMul returning u8)(self, other)
  };
}

noir_trait_impl[std.impl_144]<> std::ops::arith::Mul<> for u1 where [] := {
  noir_def mul<>(self: u1, other: u1) -> u1 := {
    (#_uMul returning u1)(self, other)
  };
}

noir_trait_impl[std.impl_145]<> std::ops::arith::Mul<> for i8 where [] := {
  noir_def mul<>(self: i8, other: i8) -> i8 := {
    (#_iMul returning i8)(self, other)
  };
}

noir_trait_impl[std.impl_146]<> std::ops::arith::Mul<> for i16 where [] := {
  noir_def mul<>(self: i16, other: i16) -> i16 := {
    (#_iMul returning i16)(self, other)
  };
}

noir_trait_impl[std.impl_147]<> std::ops::arith::Mul<> for i32 where [] := {
  noir_def mul<>(self: i32, other: i32) -> i32 := {
    (#_iMul returning i32)(self, other)
  };
}

noir_trait_impl[std.impl_148]<> std::ops::arith::Mul<> for i64 where [] := {
  noir_def mul<>(self: i64, other: i64) -> i64 := {
    (#_iMul returning i64)(self, other)
  };
}

noir_trait_impl[std.impl_149]<> std::ops::arith::Div<> for Field where [] := {
  noir_def div<>(self: Field, other: Field) -> Field := {
    (#_fDiv returning Field)(self, other)
  };
}

noir_trait_impl[std.impl_150]<> std::ops::arith::Div<> for u128 where [] := {
  noir_def div<>(self: u128, other: u128) -> u128 := {
    (#_uDiv returning u128)(self, other)
  };
}

noir_trait_impl[std.impl_151]<> std::ops::arith::Div<> for u64 where [] := {
  noir_def div<>(self: u64, other: u64) -> u64 := {
    (#_uDiv returning u64)(self, other)
  };
}

noir_trait_impl[std.impl_152]<> std::ops::arith::Div<> for u32 where [] := {
  noir_def div<>(self: u32, other: u32) -> u32 := {
    (#_uDiv returning u32)(self, other)
  };
}

noir_trait_impl[std.impl_153]<> std::ops::arith::Div<> for u16 where [] := {
  noir_def div<>(self: u16, other: u16) -> u16 := {
    (#_uDiv returning u16)(self, other)
  };
}

noir_trait_impl[std.impl_154]<> std::ops::arith::Div<> for u8 where [] := {
  noir_def div<>(self: u8, other: u8) -> u8 := {
    (#_uDiv returning u8)(self, other)
  };
}

noir_trait_impl[std.impl_155]<> std::ops::arith::Div<> for u1 where [] := {
  noir_def div<>(self: u1, other: u1) -> u1 := {
    (#_uDiv returning u1)(self, other)
  };
}

noir_trait_impl[std.impl_156]<> std::ops::arith::Div<> for i8 where [] := {
  noir_def div<>(self: i8, other: i8) -> i8 := {
    (#_iDiv returning i8)(self, other)
  };
}

noir_trait_impl[std.impl_157]<> std::ops::arith::Div<> for i16 where [] := {
  noir_def div<>(self: i16, other: i16) -> i16 := {
    (#_iDiv returning i16)(self, other)
  };
}

noir_trait_impl[std.impl_158]<> std::ops::arith::Div<> for i32 where [] := {
  noir_def div<>(self: i32, other: i32) -> i32 := {
    (#_iDiv returning i32)(self, other)
  };
}

noir_trait_impl[std.impl_159]<> std::ops::arith::Div<> for i64 where [] := {
  noir_def div<>(self: i64, other: i64) -> i64 := {
    (#_iDiv returning i64)(self, other)
  };
}

noir_trait_impl[std.impl_160]<> std::ops::arith::Rem<> for u128 where [] := {
  noir_def rem<>(self: u128, other: u128) -> u128 := {
    (#_uRem returning u128)(self, other)
  };
}

noir_trait_impl[std.impl_161]<> std::ops::arith::Rem<> for u64 where [] := {
  noir_def rem<>(self: u64, other: u64) -> u64 := {
    (#_uRem returning u64)(self, other)
  };
}

noir_trait_impl[std.impl_162]<> std::ops::arith::Rem<> for u32 where [] := {
  noir_def rem<>(self: u32, other: u32) -> u32 := {
    (#_uRem returning u32)(self, other)
  };
}

noir_trait_impl[std.impl_163]<> std::ops::arith::Rem<> for u16 where [] := {
  noir_def rem<>(self: u16, other: u16) -> u16 := {
    (#_uRem returning u16)(self, other)
  };
}

noir_trait_impl[std.impl_164]<> std::ops::arith::Rem<> for u8 where [] := {
  noir_def rem<>(self: u8, other: u8) -> u8 := {
    (#_uRem returning u8)(self, other)
  };
}

noir_trait_impl[std.impl_165]<> std::ops::arith::Rem<> for u1 where [] := {
  noir_def rem<>(self: u1, other: u1) -> u1 := {
    (#_uRem returning u1)(self, other)
  };
}

noir_trait_impl[std.impl_166]<> std::ops::arith::Rem<> for i8 where [] := {
  noir_def rem<>(self: i8, other: i8) -> i8 := {
    (#_iRem returning i8)(self, other)
  };
}

noir_trait_impl[std.impl_167]<> std::ops::arith::Rem<> for i16 where [] := {
  noir_def rem<>(self: i16, other: i16) -> i16 := {
    (#_iRem returning i16)(self, other)
  };
}

noir_trait_impl[std.impl_168]<> std::ops::arith::Rem<> for i32 where [] := {
  noir_def rem<>(self: i32, other: i32) -> i32 := {
    (#_iRem returning i32)(self, other)
  };
}

noir_trait_impl[std.impl_169]<> std::ops::arith::Rem<> for i64 where [] := {
  noir_def rem<>(self: i64, other: i64) -> i64 := {
    (#_iRem returning i64)(self, other)
  };
}

noir_trait_impl[std.impl_170]<> std::ops::arith::Neg<> for Field where [] := {
  noir_def neg<>(self: Field) -> Field := {
    (#_fNeg returning Field)(self)
  };
}

noir_trait_impl[std.impl_171]<> std::ops::arith::Neg<> for i8 where [] := {
  noir_def neg<>(self: i8) -> i8 := {
    (#_iNeg returning i8)(self)
  };
}

noir_trait_impl[std.impl_172]<> std::ops::arith::Neg<> for i16 where [] := {
  noir_def neg<>(self: i16) -> i16 := {
    (#_iNeg returning i16)(self)
  };
}

noir_trait_impl[std.impl_173]<> std::ops::arith::Neg<> for i32 where [] := {
  noir_def neg<>(self: i32) -> i32 := {
    (#_iNeg returning i32)(self)
  };
}

noir_trait_impl[std.impl_174]<> std::ops::arith::Neg<> for i64 where [] := {
  noir_def neg<>(self: i64) -> i64 := {
    (#_iNeg returning i64)(self)
  };
}

noir_trait_impl[std.impl_175]<> std::ops::arith::WrappingAdd<> for u1 where [] := {
  noir_def wrapping_add<>(self: u1, y: u1) -> u1 := {
    (#_uXor returning u1)(self, y)
  };
}

noir_trait_impl[std.impl_176]<> std::ops::arith::WrappingAdd<> for u8 where [] := {
  noir_def wrapping_add<>(self: u8, y: u8) -> u8 := {
    (std::ops::arith::wrapping_add_hlp<u8> as λ(u8, u8) -> u8)(self, y)
  };
}

noir_trait_impl[std.impl_177]<> std::ops::arith::WrappingAdd<> for u16 where [] := {
  noir_def wrapping_add<>(self: u16, y: u16) -> u16 := {
    (std::ops::arith::wrapping_add_hlp<u16> as λ(u16, u16) -> u16)(self, y)
  };
}

noir_trait_impl[std.impl_178]<> std::ops::arith::WrappingAdd<> for u32 where [] := {
  noir_def wrapping_add<>(self: u32, y: u32) -> u32 := {
    (std::ops::arith::wrapping_add_hlp<u32> as λ(u32, u32) -> u32)(self, y)
  };
}

noir_trait_impl[std.impl_179]<> std::ops::arith::WrappingAdd<> for u64 where [] := {
  noir_def wrapping_add<>(self: u64, y: u64) -> u64 := {
    (std::ops::arith::wrapping_add_hlp<u64> as λ(u64, u64) -> u64)(self, y)
  };
}

noir_trait_impl[std.impl_180]<> std::ops::arith::WrappingAdd<> for u128 where [] := {
  noir_def wrapping_add<>(self: u128, y: u128) -> u128 := {
    (std::ops::arith::wrapping_add_hlp<u128> as λ(u128, u128) -> u128)(self, y)
  };
}

noir_trait_impl[std.impl_181]<> std::ops::arith::WrappingAdd<> for i8 where [] := {
  noir_def wrapping_add<>(self: i8, y: i8) -> i8 := {
    let x = (#_cast returning u8)(self);
    (#_cast returning i8)(((u8 as std::ops::arith::WrappingAdd<>)::wrapping_add<> as λ(u8, u8) -> u8)(x, (#_cast returning u8)(y)))
  };
}

noir_trait_impl[std.impl_182]<> std::ops::arith::WrappingAdd<> for i16 where [] := {
  noir_def wrapping_add<>(self: i16, y: i16) -> i16 := {
    let x = (#_cast returning u16)(self);
    (#_cast returning i16)(((u16 as std::ops::arith::WrappingAdd<>)::wrapping_add<> as λ(u16, u16) -> u16)(x, (#_cast returning u16)(y)))
  };
}

noir_trait_impl[std.impl_183]<> std::ops::arith::WrappingAdd<> for i32 where [] := {
  noir_def wrapping_add<>(self: i32, y: i32) -> i32 := {
    let x = (#_cast returning u32)(self);
    (#_cast returning i32)(((u32 as std::ops::arith::WrappingAdd<>)::wrapping_add<> as λ(u32, u32) -> u32)(x, (#_cast returning u32)(y)))
  };
}

noir_trait_impl[std.impl_184]<> std::ops::arith::WrappingAdd<> for i64 where [] := {
  noir_def wrapping_add<>(self: i64, y: i64) -> i64 := {
    let x = (#_cast returning u64)(self);
    (#_cast returning i64)(((u64 as std::ops::arith::WrappingAdd<>)::wrapping_add<> as λ(u64, u64) -> u64)(x, (#_cast returning u64)(y)))
  };
}

noir_trait_impl[std.impl_185]<> std::ops::arith::WrappingAdd<> for Field where [] := {
  noir_def wrapping_add<>(self: Field, y: Field) -> Field := {
    (#_fAdd returning Field)(self, y)
  };
}

noir_trait_impl[std.impl_186]<> std::ops::arith::WrappingSub<> for u1 where [] := {
  noir_def wrapping_sub<>(self: u1, y: u1) -> u1 := {
    (#_uXor returning u1)(self, y)
  };
}

noir_trait_impl[std.impl_187]<> std::ops::arith::WrappingSub<> for u8 where [] := {
  noir_def wrapping_sub<>(self: u8, y: u8) -> u8 := {
    (#_cast returning u8)((std::ops::arith::wrapping_sub_hlp<u8> as λ(u8, u8) -> Field)(self, y))
  };
}

noir_trait_impl[std.impl_188]<> std::ops::arith::WrappingSub<> for u16 where [] := {
  noir_def wrapping_sub<>(self: u16, y: u16) -> u16 := {
    (#_cast returning u16)((std::ops::arith::wrapping_sub_hlp<u16> as λ(u16, u16) -> Field)(self, y))
  };
}

noir_trait_impl[std.impl_189]<> std::ops::arith::WrappingSub<> for u32 where [] := {
  noir_def wrapping_sub<>(self: u32, y: u32) -> u32 := {
    (#_cast returning u32)((std::ops::arith::wrapping_sub_hlp<u32> as λ(u32, u32) -> Field)(self, y))
  };
}

noir_trait_impl[std.impl_190]<> std::ops::arith::WrappingSub<> for u64 where [] := {
  noir_def wrapping_sub<>(self: u64, y: u64) -> u64 := {
    (#_cast returning u64)((std::ops::arith::wrapping_sub_hlp<u64> as λ(u64, u64) -> Field)(self, y))
  };
}

noir_trait_impl[std.impl_191]<> std::ops::arith::WrappingSub<> for u128 where [] := {
  noir_def wrapping_sub<>(self: u128, y: u128) -> u128 := {
    (#_cast returning u128)((std::ops::arith::wrapping_sub_hlp<u128> as λ(u128, u128) -> Field)(self, y))
  };
}

noir_trait_impl[std.impl_192]<> std::ops::arith::WrappingSub<> for i8 where [] := {
  noir_def wrapping_sub<>(self: i8, y: i8) -> i8 := {
    let x = (#_cast returning u8)(self);
    (#_cast returning i8)(((u8 as std::ops::arith::WrappingSub<>)::wrapping_sub<> as λ(u8, u8) -> u8)(x, (#_cast returning u8)(y)))
  };
}

noir_trait_impl[std.impl_193]<> std::ops::arith::WrappingSub<> for i16 where [] := {
  noir_def wrapping_sub<>(self: i16, y: i16) -> i16 := {
    let x = (#_cast returning u16)(self);
    (#_cast returning i16)(((u16 as std::ops::arith::WrappingSub<>)::wrapping_sub<> as λ(u16, u16) -> u16)(x, (#_cast returning u16)(y)))
  };
}

noir_trait_impl[std.impl_194]<> std::ops::arith::WrappingSub<> for i32 where [] := {
  noir_def wrapping_sub<>(self: i32, y: i32) -> i32 := {
    let x = (#_cast returning u32)(self);
    (#_cast returning i32)(((u32 as std::ops::arith::WrappingSub<>)::wrapping_sub<> as λ(u32, u32) -> u32)(x, (#_cast returning u32)(y)))
  };
}

noir_trait_impl[std.impl_195]<> std::ops::arith::WrappingSub<> for i64 where [] := {
  noir_def wrapping_sub<>(self: i64, y: i64) -> i64 := {
    let x = (#_cast returning u64)(self);
    (#_cast returning i64)(((u64 as std::ops::arith::WrappingSub<>)::wrapping_sub<> as λ(u64, u64) -> u64)(x, (#_cast returning u64)(y)))
  };
}

noir_trait_impl[std.impl_196]<> std::ops::arith::WrappingSub<> for Field where [] := {
  noir_def wrapping_sub<>(self: Field, y: Field) -> Field := {
    (#_fSub returning Field)(self, y)
  };
}

noir_trait_impl[std.impl_197]<> std::ops::arith::WrappingMul<> for u1 where [] := {
  noir_def wrapping_mul<>(self: u1, y: u1) -> u1 := {
    (#_uAnd returning u1)(self, y)
  };
}

noir_trait_impl[std.impl_198]<> std::ops::arith::WrappingMul<> for u8 where [] := {
  noir_def wrapping_mul<>(self: u8, y: u8) -> u8 := {
    (std::ops::arith::wrapping_mul_hlp<u8> as λ(u8, u8) -> u8)(self, y)
  };
}

noir_trait_impl[std.impl_199]<> std::ops::arith::WrappingMul<> for u16 where [] := {
  noir_def wrapping_mul<>(self: u16, y: u16) -> u16 := {
    (std::ops::arith::wrapping_mul_hlp<u16> as λ(u16, u16) -> u16)(self, y)
  };
}

noir_trait_impl[std.impl_200]<> std::ops::arith::WrappingMul<> for u32 where [] := {
  noir_def wrapping_mul<>(self: u32, y: u32) -> u32 := {
    (std::ops::arith::wrapping_mul_hlp<u32> as λ(u32, u32) -> u32)(self, y)
  };
}

noir_trait_impl[std.impl_201]<> std::ops::arith::WrappingMul<> for u64 where [] := {
  noir_def wrapping_mul<>(self: u64, y: u64) -> u64 := {
    (std::ops::arith::wrapping_mul_hlp<u64> as λ(u64, u64) -> u64)(self, y)
  };
}

noir_trait_impl[std.impl_202]<> std::ops::arith::WrappingMul<> for i8 where [] := {
  noir_def wrapping_mul<>(self: i8, y: i8) -> i8 := {
    let x = (#_cast returning u8)(self);
    (#_cast returning i8)(((u8 as std::ops::arith::WrappingMul<>)::wrapping_mul<> as λ(u8, u8) -> u8)(x, (#_cast returning u8)(y)))
  };
}

noir_trait_impl[std.impl_203]<> std::ops::arith::WrappingMul<> for i16 where [] := {
  noir_def wrapping_mul<>(self: i16, y: i16) -> i16 := {
    let x = (#_cast returning u16)(self);
    (#_cast returning i16)(((u16 as std::ops::arith::WrappingMul<>)::wrapping_mul<> as λ(u16, u16) -> u16)(x, (#_cast returning u16)(y)))
  };
}

noir_trait_impl[std.impl_204]<> std::ops::arith::WrappingMul<> for i32 where [] := {
  noir_def wrapping_mul<>(self: i32, y: i32) -> i32 := {
    let x = (#_cast returning u32)(self);
    (#_cast returning i32)(((u32 as std::ops::arith::WrappingMul<>)::wrapping_mul<> as λ(u32, u32) -> u32)(x, (#_cast returning u32)(y)))
  };
}

noir_trait_impl[std.impl_205]<> std::ops::arith::WrappingMul<> for i64 where [] := {
  noir_def wrapping_mul<>(self: i64, y: i64) -> i64 := {
    let x = (#_cast returning u64)(self);
    (#_cast returning i64)(((u64 as std::ops::arith::WrappingMul<>)::wrapping_mul<> as λ(u64, u64) -> u64)(x, (#_cast returning u64)(y)))
  };
}

noir_trait_impl[std.impl_206]<> std::ops::arith::WrappingMul<> for u128 where [] := {
  noir_def wrapping_mul<>(self: u128, y: u128) -> u128 := {
    (std::ops::arith::wrapping_mul128_hlp<> as λ(u128, u128) -> u128)(self, y)
  };
}

noir_trait_impl[std.impl_207]<> std::ops::arith::WrappingMul<> for Field where [] := {
  noir_def wrapping_mul<>(self: Field, y: Field) -> Field := {
    (#_fMul returning Field)(self, y)
  };
}

noir_def std::ops::arith::wrapping_add_hlp<T: Type>(x: T, y: T) -> T := {
  ((Field as std::convert::AsPrimitive<T>)::as_<> as λ(Field) -> T)((#_fAdd returning Field)(((T as std::convert::AsPrimitive<Field>)::as_<> as λ(T) -> Field)(x), ((T as std::convert::AsPrimitive<Field>)::as_<> as λ(T) -> Field)(y)))
}

noir_def std::ops::arith::wrapping_sub_hlp<T: Type>(x: T, y: T) -> Field := {
  (#_fSub returning Field)((#_fAdd returning Field)(((T as std::convert::AsPrimitive<Field>)::as_<> as λ(T) -> Field)(x), (340282366920938463463374607431768211456: Field)), ((T as std::convert::AsPrimitive<Field>)::as_<> as λ(T) -> Field)(y))
}

noir_def std::ops::arith::wrapping_mul_hlp<T: Type>(x: T, y: T) -> T := {
  ((Field as std::convert::AsPrimitive<T>)::as_<> as λ(Field) -> T)((#_fMul returning Field)(((T as std::convert::AsPrimitive<Field>)::as_<> as λ(T) -> Field)(x), ((T as std::convert::AsPrimitive<Field>)::as_<> as λ(T) -> Field)(y)))
}

noir_global_def std::ops::arith::two_pow_64: u128 = (18446744073709551616: u128);

noir_def std::ops::arith::split64<>(x: u128) -> Tuple<u64, u64> := {
  (#_fresh returning Tuple<u64, u64>)()
}

noir_def std::ops::arith::split_into_64_bit_limbs<>(x: u128) -> Tuple<u64, u64> := {
  let (x_lo, x_hi) = {
    (std::ops::arith::split64<> as λ(u128) -> Tuple<u64, u64>)(x)
  };
  (#_assert returning Unit)((#_fEq returning bool)((#_cast returning Field)(x), (#_fAdd returning Field)((#_cast returning Field)(x_lo), (#_fMul returning Field)((#_cast returning Field)(x_hi), (#_cast returning Field)((std::ops::arith::two_pow_64<> as λ() -> u128)())))));
  (#_makeData returning Tuple<u64, u64>)(x_lo, x_hi)
}

noir_def std::ops::arith::wrapping_mul128_hlp<>(x: u128, y: u128) -> u128 := {
  let (x_lo, x_hi) = (std::ops::arith::split_into_64_bit_limbs<> as λ(u128) -> Tuple<u64, u64>)(x);
  let (y_lo, y_hi) = (std::ops::arith::split_into_64_bit_limbs<> as λ(u128) -> Tuple<u64, u64>)(y);
  let low = (#_fMul returning Field)((#_cast returning Field)(x_lo), (#_cast returning Field)(y_lo));
  let lo = (#_cast returning Field)((#_cast returning u64)(low));
  let carry = (#_fDiv returning Field)((#_fSub returning Field)(low, lo), (#_cast returning Field)((std::ops::arith::two_pow_64<> as λ() -> u128)()));
  let high = (#_fAdd returning Field)((#_fAdd returning Field)((#_fMul returning Field)((#_cast returning Field)(x_lo), (#_cast returning Field)(y_hi)), (#_fMul returning Field)((#_cast returning Field)(x_hi), (#_cast returning Field)(y_lo))), carry);
  let hi = (#_cast returning Field)((#_cast returning u64)(high));
  (#_cast returning u128)((#_fAdd returning Field)(lo, (#_fMul returning Field)((#_cast returning Field)((std::ops::arith::two_pow_64<> as λ() -> u128)()), hi)))
}

noir_def std::ops::arith::tests::test_static_assert_custom_message<>() -> Unit := {
  (#_staticAssert returning Unit)((#_fEq returning bool)((1: Field), (2: Field)), "custom message");
  #_skip
}

noir_def std::ops::arith::tests::arithmetic::test_basic_arithmetic_traits<>() -> Unit := {
  (#_assert returning Unit)((#_fEq returning bool)(((Field as std::ops::arith::Add<>)::add<> as λ(Field, Field) -> Field)((5: Field), (3: Field)), (8: Field)));
  (#_assert returning Unit)((#_uEq returning bool)(((u8 as std::ops::arith::Add<>)::add<> as λ(u8, u8) -> u8)((0: u8), (255: u8)), (255: u8)));
  (#_assert returning Unit)((#_fEq returning bool)(((Field as std::ops::arith::Add<>)::add<> as λ(Field, Field) -> Field)((42: Field), (58: Field)), (100: Field)));
  (#_assert returning Unit)((#_fEq returning bool)(((Field as std::ops::arith::Sub<>)::sub<> as λ(Field, Field) -> Field)((10: Field), (3: Field)), (7: Field)));
  (#_assert returning Unit)((#_fEq returning bool)(((Field as std::ops::arith::Sub<>)::sub<> as λ(Field, Field) -> Field)((100: Field), (42: Field)), (58: Field)));
  (#_assert returning Unit)((#_fEq returning bool)(((Field as std::ops::arith::Mul<>)::mul<> as λ(Field, Field) -> Field)((6: Field), (7: Field)), (42: Field)));
  (#_assert returning Unit)((#_fEq returning bool)(((Field as std::ops::arith::Div<>)::div<> as λ(Field, Field) -> Field)((15: Field), (3: Field)), (5: Field)));
  (#_assert returning Unit)((#_uEq returning bool)(((u8 as std::ops::arith::Div<>)::div<> as λ(u8, u8) -> u8)((10: u8), (3: u8)), (3: u8)));
  (#_assert returning Unit)((#_fEq returning bool)(((Field as std::ops::arith::Div<>)::div<> as λ(Field, Field) -> Field)((15: Field), (3: Field)), (5: Field)));
  (#_assert returning Unit)((#_uEq returning bool)(((u128 as std::ops::arith::Rem<>)::rem<> as λ(u128, u128) -> u128)((17: u128), (5: u128)), (2: u128)));
  (#_assert returning Unit)((#_uEq returning bool)(((u8 as std::ops::arith::Rem<>)::rem<> as λ(u8, u8) -> u8)((10: u8), (3: u8)), (1: u8)));
  (#_assert returning Unit)((#_fEq returning bool)(((Field as std::ops::arith::Neg<>)::neg<> as λ(Field) -> Field)((42: Field)), (-42: Field)));
  (#_assert returning Unit)((#_fEq returning bool)(((Field as std::ops::arith::Neg<>)::neg<> as λ(Field) -> Field)((-10: Field)), (10: Field)));
  (#_assert returning Unit)((#_fEq returning bool)(((Field as std::ops::arith::Neg<>)::neg<> as λ(Field) -> Field)((42: Field)), (-42: Field)));
  #_skip
}

noir_def std::ops::arith::tests::arithmetic::test_division<>() -> Unit := {
  (#_assert returning Unit)((#_fEq returning bool)(((Field as std::ops::arith::Div<>)::div<> as λ(Field, Field) -> Field)((42: Field), (1: Field)), (42: Field)));
  (#_assert returning Unit)((#_fEq returning bool)(((Field as std::ops::arith::Div<>)::div<> as λ(Field, Field) -> Field)((0: Field), (1: Field)), (0: Field)));
  (#_assert returning Unit)((#_uEq returning bool)(((u8 as std::ops::arith::Div<>)::div<> as λ(u8, u8) -> u8)((255: u8), (1: u8)), (255: u8)));
  (#_assert returning Unit)((#_fEq returning bool)(((Field as std::ops::arith::Div<>)::div<> as λ(Field, Field) -> Field)((42: Field), (42: Field)), (1: Field)));
  (#_assert returning Unit)((#_fEq returning bool)(((Field as std::ops::arith::Div<>)::div<> as λ(Field, Field) -> Field)((1: Field), (1: Field)), (1: Field)));
  (#_assert returning Unit)((#_uEq returning bool)(((u128 as std::ops::arith::Rem<>)::rem<> as λ(u128, u128) -> u128)((42: u128), (42: u128)), (0: u128)));
  (#_assert returning Unit)((#_uEq returning bool)(((u128 as std::ops::arith::Rem<>)::rem<> as λ(u128, u128) -> u128)((0: u128), (42: u128)), (0: u128)));
  (#_assert returning Unit)((#_uEq returning bool)(((u128 as std::ops::arith::Rem<>)::rem<> as λ(u128, u128) -> u128)((1: u128), (42: u128)), (1: u128)));
  #_skip
}

noir_def std::ops::arith::tests::arithmetic::test_u8_sub_overflow_failure<>() -> Unit := {
  let __0 = ((u8 as std::ops::arith::Sub<>)::sub<> as λ(u8, u8) -> u8)((0: u8), (1: u8));
  #_skip
}

noir_def std::ops::arith::tests::arithmetic::test_u8_add_overflow_failure<>() -> Unit := {
  let __0 = ((u8 as std::ops::arith::Add<>)::add<> as λ(u8, u8) -> u8)((255: u8), (1: u8));
  #_skip
}

noir_def std::ops::arith::tests::arithmetic::test_u8_mul_overflow_failure<>() -> Unit := {
  let __0 = ((u8 as std::ops::arith::Mul<>)::mul<> as λ(u8, u8) -> u8)((255: u8), (2: u8));
  #_skip
}

noir_def std::ops::arith::tests::arithmetic::test_u16_sub_overflow_failure<>() -> Unit := {
  let __0 = ((u16 as std::ops::arith::Sub<>)::sub<> as λ(u16, u16) -> u16)((0: u16), (1: u16));
  #_skip
}

noir_def std::ops::arith::tests::arithmetic::test_u16_add_overflow_failure<>() -> Unit := {
  let __0 = ((u16 as std::ops::arith::Add<>)::add<> as λ(u16, u16) -> u16)((65535: u16), (1: u16));
  #_skip
}

noir_def std::ops::arith::tests::arithmetic::test_u16_mul_overflow_failure<>() -> Unit := {
  let __0 = ((u16 as std::ops::arith::Mul<>)::mul<> as λ(u16, u16) -> u16)((65535: u16), (2: u16));
  #_skip
}

noir_def std::ops::arith::tests::arithmetic::test_signed_sub_overflow_failure<>() -> Unit := {
  let val = (-128: i8);
  let __0 = ((i8 as std::ops::arith::Sub<>)::sub<> as λ(i8, i8) -> i8)(val, (1: i8));
  #_skip
}

noir_def std::ops::arith::tests::arithmetic::test_signed_overflow_failure<>() -> Unit := {
  let __0 = ((i8 as std::ops::arith::Add<>)::add<> as λ(i8, i8) -> i8)((127: i8), (1: i8));
  #_skip
}

noir_def std::ops::arith::tests::arithmetic::test_field<>() -> Unit := {
  let zero = (0: Field);
  let one = (1: Field);
  (#_assert returning Unit)((#_fEq returning bool)(((Field as std::ops::arith::Add<>)::add<> as λ(Field, Field) -> Field)(zero, one), one));
  (#_assert returning Unit)((#_fEq returning bool)(((Field as std::ops::arith::Add<>)::add<> as λ(Field, Field) -> Field)(one, zero), one));
  (#_assert returning Unit)((#_fEq returning bool)(((Field as std::ops::arith::Sub<>)::sub<> as λ(Field, Field) -> Field)(one, one), zero));
  (#_assert returning Unit)((#_fEq returning bool)(((Field as std::ops::arith::Mul<>)::mul<> as λ(Field, Field) -> Field)(one, one), one));
  (#_assert returning Unit)((#_fEq returning bool)(((Field as std::ops::arith::Div<>)::div<> as λ(Field, Field) -> Field)(one, one), one));
  (#_assert returning Unit)((#_fEq returning bool)(((Field as std::ops::arith::Neg<>)::neg<> as λ(Field) -> Field)(zero), zero));
  (#_assert returning Unit)((#_fEq returning bool)(((Field as std::ops::arith::Neg<>)::neg<> as λ(Field) -> Field)(one), (#_fNeg returning Field)(one)));
  #_skip
}

noir_def std::ops::arith::tests::wrapping_arithmetic::test_wrapping_add<>() -> Unit := {
  (#_assert returning Unit)((#_uEq returning bool)(((u8 as std::ops::arith::WrappingAdd<>)::wrapping_add<> as λ(u8, u8) -> u8)((255: u8), (1: u8)), (0: u8)));
  (#_assert returning Unit)((#_uEq returning bool)(((u8 as std::ops::arith::WrappingAdd<>)::wrapping_add<> as λ(u8, u8) -> u8)((255: u8), (255: u8)), (254: u8)));
  (#_assert returning Unit)((#_uEq returning bool)(((u8 as std::ops::arith::WrappingAdd<>)::wrapping_add<> as λ(u8, u8) -> u8)((0: u8), (0: u8)), (0: u8)));
  (#_assert returning Unit)((#_uEq returning bool)(((u8 as std::ops::arith::WrappingAdd<>)::wrapping_add<> as λ(u8, u8) -> u8)((128: u8), (128: u8)), (0: u8)));
  (#_assert returning Unit)((#_uEq returning bool)(((u16 as std::ops::arith::WrappingAdd<>)::wrapping_add<> as λ(u16, u16) -> u16)((65535: u16), (1: u16)), (0: u16)));
  (#_assert returning Unit)((#_uEq returning bool)(((u16 as std::ops::arith::WrappingAdd<>)::wrapping_add<> as λ(u16, u16) -> u16)((65535: u16), (65535: u16)), (65534: u16)));
  (#_assert returning Unit)((#_uEq returning bool)(((u32 as std::ops::arith::WrappingAdd<>)::wrapping_add<> as λ(u32, u32) -> u32)((4294967295: u32), (1: u32)), (0: u32)));
  (#_assert returning Unit)((#_uEq returning bool)(((u32 as std::ops::arith::WrappingAdd<>)::wrapping_add<> as λ(u32, u32) -> u32)((4294967295: u32), (4294967295: u32)), (4294967294: u32)));
  (#_assert returning Unit)((#_uEq returning bool)(((u64 as std::ops::arith::WrappingAdd<>)::wrapping_add<> as λ(u64, u64) -> u64)((18446744073709551615: u64), (1: u64)), (0: u64)));
  (#_assert returning Unit)((#_uEq returning bool)(((u64 as std::ops::arith::WrappingAdd<>)::wrapping_add<> as λ(u64, u64) -> u64)((18446744073709551615: u64), (18446744073709551615: u64)), (18446744073709551614: u64)));
  (#_assert returning Unit)((#_uEq returning bool)(((u128 as std::ops::arith::WrappingAdd<>)::wrapping_add<> as λ(u128, u128) -> u128)((340282366920938463463374607431768211455: u128), (1: u128)), (0: u128)));
  (#_assert returning Unit)((#_iEq returning bool)(((i8 as std::ops::arith::WrappingAdd<>)::wrapping_add<> as λ(i8, i8) -> i8)((127: i8), (1: i8)), (-128: i8)));
  let val = (-128: i8);
  (#_assert returning Unit)((#_iEq returning bool)(((i8 as std::ops::arith::WrappingAdd<>)::wrapping_add<> as λ(i8, i8) -> i8)(val, (-1: i8)), (127: i8)));
  let forty_two = (42: Field);
  let fifty_eight = (58: Field);
  let hundred = (100: Field);
  let neg_two = (-2: Field);
  let two = (2: Field);
  let zero = (0: Field);
  let neg_two_hundred = (-200: Field);
  let neg_one_ninety_eight = (-198: Field);
  (#_assert returning Unit)((#_fEq returning bool)(((Field as std::ops::arith::WrappingAdd<>)::wrapping_add<> as λ(Field, Field) -> Field)(forty_two, fifty_eight), hundred));
  (#_assert returning Unit)((#_fEq returning bool)(((Field as std::ops::arith::WrappingAdd<>)::wrapping_add<> as λ(Field, Field) -> Field)(neg_two, two), zero));
  (#_assert returning Unit)((#_fEq returning bool)(((Field as std::ops::arith::WrappingAdd<>)::wrapping_add<> as λ(Field, Field) -> Field)(neg_two_hundred, two), neg_one_ninety_eight));
  #_skip
}

noir_def std::ops::arith::tests::wrapping_arithmetic::test_wrapping_sub<>() -> Unit := {
  (#_assert returning Unit)((#_uEq returning bool)(((u8 as std::ops::arith::WrappingSub<>)::wrapping_sub<> as λ(u8, u8) -> u8)((0: u8), (1: u8)), (255: u8)));
  (#_assert returning Unit)((#_uEq returning bool)(((u8 as std::ops::arith::WrappingSub<>)::wrapping_sub<> as λ(u8, u8) -> u8)((255: u8), (255: u8)), (0: u8)));
  (#_assert returning Unit)((#_uEq returning bool)(((u8 as std::ops::arith::WrappingSub<>)::wrapping_sub<> as λ(u8, u8) -> u8)((0: u8), (0: u8)), (0: u8)));
  (#_assert returning Unit)((#_uEq returning bool)(((u8 as std::ops::arith::WrappingSub<>)::wrapping_sub<> as λ(u8, u8) -> u8)((1: u8), (2: u8)), (255: u8)));
  (#_assert returning Unit)((#_uEq returning bool)(((u16 as std::ops::arith::WrappingSub<>)::wrapping_sub<> as λ(u16, u16) -> u16)((0: u16), (1: u16)), (65535: u16)));
  (#_assert returning Unit)((#_uEq returning bool)(((u16 as std::ops::arith::WrappingSub<>)::wrapping_sub<> as λ(u16, u16) -> u16)((65535: u16), (65535: u16)), (0: u16)));
  (#_assert returning Unit)((#_uEq returning bool)(((u32 as std::ops::arith::WrappingSub<>)::wrapping_sub<> as λ(u32, u32) -> u32)((0: u32), (1: u32)), (4294967295: u32)));
  (#_assert returning Unit)((#_uEq returning bool)(((u32 as std::ops::arith::WrappingSub<>)::wrapping_sub<> as λ(u32, u32) -> u32)((4294967295: u32), (4294967295: u32)), (0: u32)));
  (#_assert returning Unit)((#_uEq returning bool)(((u64 as std::ops::arith::WrappingSub<>)::wrapping_sub<> as λ(u64, u64) -> u64)((0: u64), (1: u64)), (18446744073709551615: u64)));
  (#_assert returning Unit)((#_uEq returning bool)(((u64 as std::ops::arith::WrappingSub<>)::wrapping_sub<> as λ(u64, u64) -> u64)((18446744073709551615: u64), (18446744073709551615: u64)), (0: u64)));
  (#_assert returning Unit)((#_uEq returning bool)(((u128 as std::ops::arith::WrappingSub<>)::wrapping_sub<> as λ(u128, u128) -> u128)((0: u128), (1: u128)), (340282366920938463463374607431768211455: u128)));
  let val = (-128: i8);
  (#_assert returning Unit)((#_iEq returning bool)(((i8 as std::ops::arith::WrappingSub<>)::wrapping_sub<> as λ(i8, i8) -> i8)(val, (1: i8)), (127: i8)));
  (#_assert returning Unit)((#_iEq returning bool)(((i8 as std::ops::arith::WrappingSub<>)::wrapping_sub<> as λ(i8, i8) -> i8)((127: i8), (-1: i8)), (-128: i8)));
  let forty_two = (42: Field);
  let fifty_eight = (58: Field);
  let neg_sixteen = (-16: Field);
  (#_assert returning Unit)((#_fEq returning bool)(((Field as std::ops::arith::WrappingSub<>)::wrapping_sub<> as λ(Field, Field) -> Field)(forty_two, fifty_eight), neg_sixteen));
  #_skip
}

noir_def std::ops::arith::tests::wrapping_arithmetic::test_wrapping_mul<>() -> Unit := {
  let zero = (0: u128);
  let one = (1: u128);
  let two_pow_64 = (18446744073709551616: u128);
  let u128_max = (340282366920938463463374607431768211455: u128);
  (#_assert returning Unit)((#_uEq returning bool)(zero, ((u128 as std::ops::arith::WrappingMul<>)::wrapping_mul<> as λ(u128, u128) -> u128)(zero, one)));
  (#_assert returning Unit)((#_uEq returning bool)(zero, ((u128 as std::ops::arith::WrappingMul<>)::wrapping_mul<> as λ(u128, u128) -> u128)(one, zero)));
  (#_assert returning Unit)((#_uEq returning bool)(one, ((u128 as std::ops::arith::WrappingMul<>)::wrapping_mul<> as λ(u128, u128) -> u128)(one, one)));
  (#_assert returning Unit)((#_uEq returning bool)(zero, ((u128 as std::ops::arith::WrappingMul<>)::wrapping_mul<> as λ(u128, u128) -> u128)(zero, two_pow_64)));
  (#_assert returning Unit)((#_uEq returning bool)(zero, ((u128 as std::ops::arith::WrappingMul<>)::wrapping_mul<> as λ(u128, u128) -> u128)(two_pow_64, zero)));
  (#_assert returning Unit)((#_uEq returning bool)(two_pow_64, ((u128 as std::ops::arith::WrappingMul<>)::wrapping_mul<> as λ(u128, u128) -> u128)(two_pow_64, one)));
  (#_assert returning Unit)((#_uEq returning bool)(two_pow_64, ((u128 as std::ops::arith::WrappingMul<>)::wrapping_mul<> as λ(u128, u128) -> u128)(one, two_pow_64)));
  (#_assert returning Unit)((#_uEq returning bool)(zero, ((u128 as std::ops::arith::WrappingMul<>)::wrapping_mul<> as λ(u128, u128) -> u128)(two_pow_64, two_pow_64)));
  (#_assert returning Unit)((#_uEq returning bool)(one, ((u128 as std::ops::arith::WrappingMul<>)::wrapping_mul<> as λ(u128, u128) -> u128)(u128_max, u128_max)));
  (#_assert returning Unit)((#_uEq returning bool)(((u8 as std::ops::arith::WrappingMul<>)::wrapping_mul<> as λ(u8, u8) -> u8)((255: u8), (2: u8)), (254: u8)));
  (#_assert returning Unit)((#_uEq returning bool)(((u8 as std::ops::arith::WrappingMul<>)::wrapping_mul<> as λ(u8, u8) -> u8)((255: u8), (255: u8)), (1: u8)));
  (#_assert returning Unit)((#_uEq returning bool)(((u8 as std::ops::arith::WrappingMul<>)::wrapping_mul<> as λ(u8, u8) -> u8)((128: u8), (2: u8)), (0: u8)));
  (#_assert returning Unit)((#_uEq returning bool)(((u16 as std::ops::arith::WrappingMul<>)::wrapping_mul<> as λ(u16, u16) -> u16)((65535: u16), (2: u16)), (65534: u16)));
  (#_assert returning Unit)((#_uEq returning bool)(((u16 as std::ops::arith::WrappingMul<>)::wrapping_mul<> as λ(u16, u16) -> u16)((65535: u16), (65535: u16)), (1: u16)));
  (#_assert returning Unit)((#_uEq returning bool)(((u32 as std::ops::arith::WrappingMul<>)::wrapping_mul<> as λ(u32, u32) -> u32)((4294967295: u32), (2: u32)), (4294967294: u32)));
  (#_assert returning Unit)((#_uEq returning bool)(((u32 as std::ops::arith::WrappingMul<>)::wrapping_mul<> as λ(u32, u32) -> u32)((4294967295: u32), (4294967295: u32)), (1: u32)));
  (#_assert returning Unit)((#_uEq returning bool)(((u64 as std::ops::arith::WrappingMul<>)::wrapping_mul<> as λ(u64, u64) -> u64)((18446744073709551615: u64), (2: u64)), (18446744073709551614: u64)));
  (#_assert returning Unit)((#_uEq returning bool)(((u64 as std::ops::arith::WrappingMul<>)::wrapping_mul<> as λ(u64, u64) -> u64)((18446744073709551615: u64), (18446744073709551615: u64)), (1: u64)));
  (#_assert returning Unit)((#_iEq returning bool)(((i8 as std::ops::arith::WrappingMul<>)::wrapping_mul<> as λ(i8, i8) -> i8)((127: i8), (2: i8)), (-2: i8)));
  let val = (-128: i8);
  (#_assert returning Unit)((#_iEq returning bool)(((i8 as std::ops::arith::WrappingMul<>)::wrapping_mul<> as λ(i8, i8) -> i8)(val, (-1: i8)), (-128: i8)));
  let six = (6: Field);
  let seven = (7: Field);
  let forty_two = (42: Field);
  let neg_two = (-2: Field);
  let two = (2: Field);
  let neg_four = (-4: Field);
  (#_assert returning Unit)((#_fEq returning bool)(((Field as std::ops::arith::WrappingMul<>)::wrapping_mul<> as λ(Field, Field) -> Field)(six, seven), forty_two));
  (#_assert returning Unit)((#_fEq returning bool)(((Field as std::ops::arith::WrappingMul<>)::wrapping_mul<> as λ(Field, Field) -> Field)(neg_two, two), neg_four));
  #_skip
}

noir_def std::ops::arith::tests::wrapping_arithmetic::test_u1_behavior<>() -> Unit := {
  (#_assert returning Unit)((#_uEq returning bool)(((u1 as std::ops::arith::WrappingAdd<>)::wrapping_add<> as λ(u1, u1) -> u1)((0: u1), (0: u1)), (0: u1)));
  (#_assert returning Unit)((#_uEq returning bool)(((u1 as std::ops::arith::WrappingAdd<>)::wrapping_add<> as λ(u1, u1) -> u1)((0: u1), (1: u1)), (1: u1)));
  (#_assert returning Unit)((#_uEq returning bool)(((u1 as std::ops::arith::WrappingAdd<>)::wrapping_add<> as λ(u1, u1) -> u1)((1: u1), (0: u1)), (1: u1)));
  (#_assert returning Unit)((#_uEq returning bool)(((u1 as std::ops::arith::WrappingAdd<>)::wrapping_add<> as λ(u1, u1) -> u1)((1: u1), (1: u1)), (0: u1)));
  (#_assert returning Unit)((#_uEq returning bool)(((u1 as std::ops::arith::WrappingSub<>)::wrapping_sub<> as λ(u1, u1) -> u1)((0: u1), (0: u1)), (0: u1)));
  (#_assert returning Unit)((#_uEq returning bool)(((u1 as std::ops::arith::WrappingSub<>)::wrapping_sub<> as λ(u1, u1) -> u1)((0: u1), (1: u1)), (1: u1)));
  (#_assert returning Unit)((#_uEq returning bool)(((u1 as std::ops::arith::WrappingSub<>)::wrapping_sub<> as λ(u1, u1) -> u1)((1: u1), (0: u1)), (1: u1)));
  (#_assert returning Unit)((#_uEq returning bool)(((u1 as std::ops::arith::WrappingSub<>)::wrapping_sub<> as λ(u1, u1) -> u1)((1: u1), (1: u1)), (0: u1)));
  (#_assert returning Unit)((#_uEq returning bool)(((u1 as std::ops::arith::WrappingMul<>)::wrapping_mul<> as λ(u1, u1) -> u1)((0: u1), (0: u1)), (0: u1)));
  (#_assert returning Unit)((#_uEq returning bool)(((u1 as std::ops::arith::WrappingMul<>)::wrapping_mul<> as λ(u1, u1) -> u1)((0: u1), (1: u1)), (0: u1)));
  (#_assert returning Unit)((#_uEq returning bool)(((u1 as std::ops::arith::WrappingMul<>)::wrapping_mul<> as λ(u1, u1) -> u1)((1: u1), (0: u1)), (0: u1)));
  (#_assert returning Unit)((#_uEq returning bool)(((u1 as std::ops::arith::WrappingMul<>)::wrapping_mul<> as λ(u1, u1) -> u1)((1: u1), (1: u1)), (1: u1)));
  #_skip
}

noir_def std::ops::arith::tests::wrapping_arithmetic::test_wrapping_vs_regular<>() -> Unit := {
  let u64_large = (1311768467463790320: u64);
  let u128_large = (24197857203266734864793317670504947440: u128);
  (#_assert returning Unit)((#_uEq returning bool)(((u64 as std::ops::arith::WrappingAdd<>)::wrapping_add<> as λ(u64, u64) -> u64)(u64_large, (1: u64)), (#_uAdd returning u64)(u64_large, (1: u64))));
  (#_assert returning Unit)((#_uEq returning bool)(((u64 as std::ops::arith::WrappingSub<>)::wrapping_sub<> as λ(u64, u64) -> u64)(u64_large, (1: u64)), (#_uSub returning u64)(u64_large, (1: u64))));
  (#_assert returning Unit)((#_uEq returning bool)(((u64 as std::ops::arith::WrappingMul<>)::wrapping_mul<> as λ(u64, u64) -> u64)(u64_large, (2: u64)), (#_uMul returning u64)(u64_large, (2: u64))));
  (#_assert returning Unit)((#_uEq returning bool)(((u128 as std::ops::arith::WrappingAdd<>)::wrapping_add<> as λ(u128, u128) -> u128)(u128_large, (1: u128)), (#_uAdd returning u128)(u128_large, (1: u128))));
  (#_assert returning Unit)((#_uEq returning bool)(((u128 as std::ops::arith::WrappingSub<>)::wrapping_sub<> as λ(u128, u128) -> u128)(u128_large, (1: u128)), (#_uSub returning u128)(u128_large, (1: u128))));
  (#_assert returning Unit)((#_uEq returning bool)(((u128 as std::ops::arith::WrappingMul<>)::wrapping_mul<> as λ(u128, u128) -> u128)(u128_large, (2: u128)), (#_uMul returning u128)(u128_large, (2: u128))));
  #_skip
}

noir_def std::ops::arith::tests::wrapping_arithmetic::test_field_wrapping_operations<>() -> Unit := {
  let zero = (0: Field);
  let one = (1: Field);
  let large_val = (18446744073709551615: Field);
  (#_assert returning Unit)((#_fEq returning bool)(((Field as std::ops::arith::WrappingAdd<>)::wrapping_add<> as λ(Field, Field) -> Field)(zero, one), one));
  (#_assert returning Unit)((#_fEq returning bool)(((Field as std::ops::arith::WrappingAdd<>)::wrapping_add<> as λ(Field, Field) -> Field)(one, large_val), (#_fAdd returning Field)(one, large_val)));
  (#_assert returning Unit)((#_fEq returning bool)(((Field as std::ops::arith::WrappingSub<>)::wrapping_sub<> as λ(Field, Field) -> Field)(zero, one), (#_fNeg returning Field)(one)));
  (#_assert returning Unit)((#_fEq returning bool)(((Field as std::ops::arith::WrappingSub<>)::wrapping_sub<> as λ(Field, Field) -> Field)(one, large_val), (#_fSub returning Field)(one, large_val)));
  (#_assert returning Unit)((#_fEq returning bool)(((Field as std::ops::arith::WrappingMul<>)::wrapping_mul<> as λ(Field, Field) -> Field)(zero, one), zero));
  (#_assert returning Unit)((#_fEq returning bool)(((Field as std::ops::arith::WrappingMul<>)::wrapping_mul<> as λ(Field, Field) -> Field)(one, large_val), large_val));
  (#_assert returning Unit)((#_fEq returning bool)(((Field as std::ops::arith::Add<>)::add<> as λ(Field, Field) -> Field)(zero, one), one));
  (#_assert returning Unit)((#_fEq returning bool)(((Field as std::ops::arith::Add<>)::add<> as λ(Field, Field) -> Field)(one, zero), one));
  (#_assert returning Unit)((#_fEq returning bool)(((Field as std::ops::arith::Sub<>)::sub<> as λ(Field, Field) -> Field)(one, one), zero));
  (#_assert returning Unit)((#_fEq returning bool)(((Field as std::ops::arith::Mul<>)::mul<> as λ(Field, Field) -> Field)(one, one), one));
  (#_assert returning Unit)((#_fEq returning bool)(((Field as std::ops::arith::Div<>)::div<> as λ(Field, Field) -> Field)(one, one), one));
  (#_assert returning Unit)((#_fEq returning bool)(((Field as std::ops::arith::Neg<>)::neg<> as λ(Field) -> Field)(zero), zero));
  (#_assert returning Unit)((#_fEq returning bool)(((Field as std::ops::arith::Neg<>)::neg<> as λ(Field) -> Field)(one), (#_fNeg returning Field)(one)));
  #_skip
}

noir_def std::ops::arith::tests::split_functions::test_split_functions<>() -> Unit := {
  let small_val = (81985529216486895: u128);
  let large_val = (24197857203266734864793317670504947440: u128);
  let max_val = (340282366920938463463374607431768211455: u128);
  {
    let (lo, hi) = (std::ops::arith::split64<> as λ(u128) -> Tuple<u64, u64>)(small_val);
    (#_assert returning Unit)((#_uEq returning bool)(lo, (81985529216486895: u64)));
    (#_assert returning Unit)((#_uEq returning bool)(hi, (0: u64)));
    let (lo2, hi2) = (std::ops::arith::split64<> as λ(u128) -> Tuple<u64, u64>)(large_val);
    (#_assert returning Unit)((#_uEq returning bool)(lo2, (1311768467463790320: u64)));
    (#_assert returning Unit)((#_uEq returning bool)(hi2, (1311768467463790320: u64)));
    #_skip
  };
  let (lo3, hi3) = (std::ops::arith::split_into_64_bit_limbs<> as λ(u128) -> Tuple<u64, u64>)(small_val);
  (#_assert returning Unit)((#_uEq returning bool)(lo3, (81985529216486895: u64)));
  (#_assert returning Unit)((#_uEq returning bool)(hi3, (0: u64)));
  let (lo4, hi4) = (std::ops::arith::split_into_64_bit_limbs<> as λ(u128) -> Tuple<u64, u64>)(large_val);
  (#_assert returning Unit)((#_uEq returning bool)(lo4, (1311768467463790320: u64)));
  (#_assert returning Unit)((#_uEq returning bool)(hi4, (1311768467463790320: u64)));
  let (lo5, hi5) = (std::ops::arith::split_into_64_bit_limbs<> as λ(u128) -> Tuple<u64, u64>)(max_val);
  (#_assert returning Unit)((#_uEq returning bool)(lo5, (18446744073709551615: u64)));
  (#_assert returning Unit)((#_uEq returning bool)(hi5, (18446744073709551615: u64)));
  #_skip
}

def std.Ops.Arith.env : Env := Env.mk
  [«std::ops::arith::wrapping_add_hlp», «std::ops::arith::wrapping_sub_hlp», «std::ops::arith::wrapping_mul_hlp», «std::ops::arith::two_pow_64», «std::ops::arith::split64», «std::ops::arith::split_into_64_bit_limbs», «std::ops::arith::wrapping_mul128_hlp», «std::ops::arith::tests::test_static_assert_custom_message», «std::ops::arith::tests::arithmetic::test_basic_arithmetic_traits», «std::ops::arith::tests::arithmetic::test_division», «std::ops::arith::tests::arithmetic::test_u8_sub_overflow_failure», «std::ops::arith::tests::arithmetic::test_u8_add_overflow_failure», «std::ops::arith::tests::arithmetic::test_u8_mul_overflow_failure», «std::ops::arith::tests::arithmetic::test_u16_sub_overflow_failure», «std::ops::arith::tests::arithmetic::test_u16_add_overflow_failure», «std::ops::arith::tests::arithmetic::test_u16_mul_overflow_failure», «std::ops::arith::tests::arithmetic::test_signed_sub_overflow_failure», «std::ops::arith::tests::arithmetic::test_signed_overflow_failure», «std::ops::arith::tests::arithmetic::test_field», «std::ops::arith::tests::wrapping_arithmetic::test_wrapping_add», «std::ops::arith::tests::wrapping_arithmetic::test_wrapping_sub», «std::ops::arith::tests::wrapping_arithmetic::test_wrapping_mul», «std::ops::arith::tests::wrapping_arithmetic::test_u1_behavior», «std::ops::arith::tests::wrapping_arithmetic::test_wrapping_vs_regular», «std::ops::arith::tests::wrapping_arithmetic::test_field_wrapping_operations», «std::ops::arith::tests::split_functions::test_split_functions»]
  [std.impl_116, std.impl_117, std.impl_118, std.impl_119, std.impl_120, std.impl_121, std.impl_122, std.impl_123, std.impl_124, std.impl_125, std.impl_126, std.impl_127, std.impl_128, std.impl_129, std.impl_130, std.impl_131, std.impl_132, std.impl_133, std.impl_134, std.impl_135, std.impl_136, std.impl_137, std.impl_138, std.impl_139, std.impl_140, std.impl_141, std.impl_142, std.impl_143, std.impl_144, std.impl_145, std.impl_146, std.impl_147, std.impl_148, std.impl_149, std.impl_150, std.impl_151, std.impl_152, std.impl_153, std.impl_154, std.impl_155, std.impl_156, std.impl_157, std.impl_158, std.impl_159, std.impl_160, std.impl_161, std.impl_162, std.impl_163, std.impl_164, std.impl_165, std.impl_166, std.impl_167, std.impl_168, std.impl_169, std.impl_170, std.impl_171, std.impl_172, std.impl_173, std.impl_174, std.impl_175, std.impl_176, std.impl_177, std.impl_178, std.impl_179, std.impl_180, std.impl_181, std.impl_182, std.impl_183, std.impl_184, std.impl_185, std.impl_186, std.impl_187, std.impl_188, std.impl_189, std.impl_190, std.impl_191, std.impl_192, std.impl_193, std.impl_194, std.impl_195, std.impl_196, std.impl_197, std.impl_198, std.impl_199, std.impl_200, std.impl_201, std.impl_202, std.impl_203, std.impl_204, std.impl_205, std.impl_206, std.impl_207]
