-- Generated by lampe

import «Base64Test-0.0.0».Extracted.GeneratedTypes
import «Base64Test-0.0.0».Extracted.Lib
import «noir_base64-0.0.0».Extracted
import std.Extracted

namespace «Base64Test-0.0.0»

def env := Lib.env
  ++ «noir_base64-0.0.0».env
  ++ std.env
