-- Generated by lampe

import «LocalDepWithLampe-2.0.0».Extracted.GeneratedTypes
import «LocalDepWithLampe-2.0.0».Extracted.Lib
import std.Extracted

namespace «LocalDepWithLampe-2.0.0»

def env := Lib.env
  ++ std.env
