-- Generated by lampe

import std.Extracted.GeneratedTypes
import Lampe

open Lampe

set_option linter.unusedVariables false

noir_trait_impl[std.impl_315]<T: Type> std::append::Append<> for Vector<T> where [] := {
  noir_def empty<>() -> Vector<T> := {
    (#_asVector returning Vector<T>)((#_mkArray returning Array<T, 0: u32>)())
  };
  
  noir_def append<>(self: Vector<T>, other: Vector<T>) -> Vector<T> := {
    (std::vector::append<T> as λ(Vector<T>, Vector<T>) -> Vector<T>)(self, other)
  };
}

def std.Append.env : Env := Env.mk
  []
  [std.impl_315]
