-- Generated by lampe

import std.Extracted.GeneratedTypes
import Lampe

open Lampe

set_option linter.unusedVariables false

noir_trait_impl[std.impl_40]<T: Type> std::convert::From<T> for T where [] := {
  noir_def «from»<>(input: T) -> T := {
    input
  };
}

noir_trait_impl[std.impl_41]<T: Type, U: Type> std::convert::Into<T> for U where [T: std::convert::From<U>] := {
  noir_def into<>(self: U) -> T := {
    ((T as std::convert::From<U>)::«from»<> as λ(U) -> T)(self)
  };
}

noir_trait_impl[std.impl_42]<> std::convert::From<u8> for u16 where [] := {
  noir_def «from»<>(value: u8) -> u16 := {
    (#_cast returning u16)(value)
  };
}

noir_trait_impl[std.impl_43]<> std::convert::From<u8> for u32 where [] := {
  noir_def «from»<>(value: u8) -> u32 := {
    (#_cast returning u32)(value)
  };
}

noir_trait_impl[std.impl_44]<> std::convert::From<u16> for u32 where [] := {
  noir_def «from»<>(value: u16) -> u32 := {
    (#_cast returning u32)(value)
  };
}

noir_trait_impl[std.impl_45]<> std::convert::From<u8> for u64 where [] := {
  noir_def «from»<>(value: u8) -> u64 := {
    (#_cast returning u64)(value)
  };
}

noir_trait_impl[std.impl_46]<> std::convert::From<u16> for u64 where [] := {
  noir_def «from»<>(value: u16) -> u64 := {
    (#_cast returning u64)(value)
  };
}

noir_trait_impl[std.impl_47]<> std::convert::From<u32> for u64 where [] := {
  noir_def «from»<>(value: u32) -> u64 := {
    (#_cast returning u64)(value)
  };
}

noir_trait_impl[std.impl_48]<> std::convert::From<u8> for u128 where [] := {
  noir_def «from»<>(value: u8) -> u128 := {
    (#_cast returning u128)(value)
  };
}

noir_trait_impl[std.impl_49]<> std::convert::From<u16> for u128 where [] := {
  noir_def «from»<>(value: u16) -> u128 := {
    (#_cast returning u128)(value)
  };
}

noir_trait_impl[std.impl_50]<> std::convert::From<u32> for u128 where [] := {
  noir_def «from»<>(value: u32) -> u128 := {
    (#_cast returning u128)(value)
  };
}

noir_trait_impl[std.impl_51]<> std::convert::From<u64> for u128 where [] := {
  noir_def «from»<>(value: u64) -> u128 := {
    (#_cast returning u128)(value)
  };
}

noir_trait_impl[std.impl_52]<> std::convert::From<u8> for Field where [] := {
  noir_def «from»<>(value: u8) -> Field := {
    (#_cast returning Field)(value)
  };
}

noir_trait_impl[std.impl_53]<> std::convert::From<u16> for Field where [] := {
  noir_def «from»<>(value: u16) -> Field := {
    (#_cast returning Field)(value)
  };
}

noir_trait_impl[std.impl_54]<> std::convert::From<u32> for Field where [] := {
  noir_def «from»<>(value: u32) -> Field := {
    (#_cast returning Field)(value)
  };
}

noir_trait_impl[std.impl_55]<> std::convert::From<u64> for Field where [] := {
  noir_def «from»<>(value: u64) -> Field := {
    (#_cast returning Field)(value)
  };
}

noir_trait_impl[std.impl_56]<> std::convert::From<u128> for Field where [] := {
  noir_def «from»<>(value: u128) -> Field := {
    (#_cast returning Field)(value)
  };
}

noir_trait_impl[std.impl_57]<> std::convert::From< i8> for i16 where [] := {
  noir_def «from»<>(value: i8) -> i16 := {
    (#_cast returning i16)(value)
  };
}

noir_trait_impl[std.impl_58]<> std::convert::From< i8> for i32 where [] := {
  noir_def «from»<>(value: i8) -> i32 := {
    (#_cast returning i32)(value)
  };
}

noir_trait_impl[std.impl_59]<> std::convert::From< i16> for i32 where [] := {
  noir_def «from»<>(value: i16) -> i32 := {
    (#_cast returning i32)(value)
  };
}

noir_trait_impl[std.impl_60]<> std::convert::From< i8> for i64 where [] := {
  noir_def «from»<>(value: i8) -> i64 := {
    (#_cast returning i64)(value)
  };
}

noir_trait_impl[std.impl_61]<> std::convert::From< i16> for i64 where [] := {
  noir_def «from»<>(value: i16) -> i64 := {
    (#_cast returning i64)(value)
  };
}

noir_trait_impl[std.impl_62]<> std::convert::From< i32> for i64 where [] := {
  noir_def «from»<>(value: i32) -> i64 := {
    (#_cast returning i64)(value)
  };
}

noir_trait_impl[std.impl_63]<> std::convert::From<bool> for u8 where [] := {
  noir_def «from»<>(value: bool) -> u8 := {
    (#_cast returning u8)(value)
  };
}

noir_trait_impl[std.impl_64]<> std::convert::From<bool> for u16 where [] := {
  noir_def «from»<>(value: bool) -> u16 := {
    (#_cast returning u16)(value)
  };
}

noir_trait_impl[std.impl_65]<> std::convert::From<bool> for u32 where [] := {
  noir_def «from»<>(value: bool) -> u32 := {
    (#_cast returning u32)(value)
  };
}

noir_trait_impl[std.impl_66]<> std::convert::From<bool> for u64 where [] := {
  noir_def «from»<>(value: bool) -> u64 := {
    (#_cast returning u64)(value)
  };
}

noir_trait_impl[std.impl_67]<> std::convert::From<bool> for u128 where [] := {
  noir_def «from»<>(value: bool) -> u128 := {
    (#_cast returning u128)(value)
  };
}

noir_trait_impl[std.impl_68]<> std::convert::From<bool> for i8 where [] := {
  noir_def «from»<>(value: bool) -> i8 := {
    (#_cast returning i8)(value)
  };
}

noir_trait_impl[std.impl_69]<> std::convert::From<bool> for i16 where [] := {
  noir_def «from»<>(value: bool) -> i16 := {
    (#_cast returning i16)(value)
  };
}

noir_trait_impl[std.impl_70]<> std::convert::From<bool> for i32 where [] := {
  noir_def «from»<>(value: bool) -> i32 := {
    (#_cast returning i32)(value)
  };
}

noir_trait_impl[std.impl_71]<> std::convert::From<bool> for i64 where [] := {
  noir_def «from»<>(value: bool) -> i64 := {
    (#_cast returning i64)(value)
  };
}

noir_trait_impl[std.impl_72]<> std::convert::From<bool> for Field where [] := {
  noir_def «from»<>(value: bool) -> Field := {
    (#_cast returning Field)(value)
  };
}

noir_trait_impl[std.impl_349]<> std::convert::AsPrimitive<u32> for bool where [] := {
  noir_def as_<>(self: bool) -> u32 := {
    (#_cast returning u32)(self)
  };
}

noir_trait_impl[std.impl_399]<> std::convert::AsPrimitive< i32> for bool where [] := {
  noir_def as_<>(self: bool) -> i32 := {
    (#_cast returning i32)(self)
  };
}

noir_trait_impl[std.impl_319]<> std::convert::AsPrimitive<bool> for bool where [] := {
  noir_def as_<>(self: bool) -> bool := {
    self
  };
}

noir_trait_impl[std.impl_369]<> std::convert::AsPrimitive<u128> for bool where [] := {
  noir_def as_<>(self: bool) -> u128 := {
    (#_cast returning u128)(self)
  };
}

noir_trait_impl[std.impl_339]<> std::convert::AsPrimitive<u16> for bool where [] := {
  noir_def as_<>(self: bool) -> u16 := {
    (#_cast returning u16)(self)
  };
}

noir_trait_impl[std.impl_389]<> std::convert::AsPrimitive< i16> for bool where [] := {
  noir_def as_<>(self: bool) -> i16 := {
    (#_cast returning i16)(self)
  };
}

noir_trait_impl[std.impl_359]<> std::convert::AsPrimitive<u64> for bool where [] := {
  noir_def as_<>(self: bool) -> u64 := {
    (#_cast returning u64)(self)
  };
}

noir_trait_impl[std.impl_409]<> std::convert::AsPrimitive< i64> for bool where [] := {
  noir_def as_<>(self: bool) -> i64 := {
    (#_cast returning i64)(self)
  };
}

noir_trait_impl[std.impl_329]<> std::convert::AsPrimitive<u8> for bool where [] := {
  noir_def as_<>(self: bool) -> u8 := {
    (#_cast returning u8)(self)
  };
}

noir_trait_impl[std.impl_379]<> std::convert::AsPrimitive< i8> for bool where [] := {
  noir_def as_<>(self: bool) -> i8 := {
    (#_cast returning i8)(self)
  };
}

noir_trait_impl[std.impl_350]<> std::convert::AsPrimitive<u32> for u8 where [] := {
  noir_def as_<>(self: u8) -> u32 := {
    (#_cast returning u32)(self)
  };
}

noir_trait_impl[std.impl_400]<> std::convert::AsPrimitive< i32> for u8 where [] := {
  noir_def as_<>(self: u8) -> i32 := {
    (#_cast returning i32)(self)
  };
}

noir_trait_impl[std.impl_320]<> std::convert::AsPrimitive<bool> for u8 where [] := {
  noir_def as_<>(self: u8) -> bool := {
    (#_uNeq returning bool)(self, (0: u8))
  };
}

noir_trait_impl[std.impl_370]<> std::convert::AsPrimitive<u128> for u8 where [] := {
  noir_def as_<>(self: u8) -> u128 := {
    (#_cast returning u128)(self)
  };
}

noir_trait_impl[std.impl_340]<> std::convert::AsPrimitive<u16> for u8 where [] := {
  noir_def as_<>(self: u8) -> u16 := {
    (#_cast returning u16)(self)
  };
}

noir_trait_impl[std.impl_390]<> std::convert::AsPrimitive< i16> for u8 where [] := {
  noir_def as_<>(self: u8) -> i16 := {
    (#_cast returning i16)(self)
  };
}

noir_trait_impl[std.impl_360]<> std::convert::AsPrimitive<u64> for u8 where [] := {
  noir_def as_<>(self: u8) -> u64 := {
    (#_cast returning u64)(self)
  };
}

noir_trait_impl[std.impl_410]<> std::convert::AsPrimitive< i64> for u8 where [] := {
  noir_def as_<>(self: u8) -> i64 := {
    (#_cast returning i64)(self)
  };
}

noir_trait_impl[std.impl_330]<> std::convert::AsPrimitive<u8> for u8 where [] := {
  noir_def as_<>(self: u8) -> u8 := {
    self
  };
}

noir_trait_impl[std.impl_380]<> std::convert::AsPrimitive< i8> for u8 where [] := {
  noir_def as_<>(self: u8) -> i8 := {
    (#_cast returning i8)(self)
  };
}

noir_trait_impl[std.impl_351]<> std::convert::AsPrimitive<u32> for u16 where [] := {
  noir_def as_<>(self: u16) -> u32 := {
    (#_cast returning u32)(self)
  };
}

noir_trait_impl[std.impl_401]<> std::convert::AsPrimitive< i32> for u16 where [] := {
  noir_def as_<>(self: u16) -> i32 := {
    (#_cast returning i32)(self)
  };
}

noir_trait_impl[std.impl_321]<> std::convert::AsPrimitive<bool> for u16 where [] := {
  noir_def as_<>(self: u16) -> bool := {
    (#_uNeq returning bool)(self, (0: u16))
  };
}

noir_trait_impl[std.impl_371]<> std::convert::AsPrimitive<u128> for u16 where [] := {
  noir_def as_<>(self: u16) -> u128 := {
    (#_cast returning u128)(self)
  };
}

noir_trait_impl[std.impl_341]<> std::convert::AsPrimitive<u16> for u16 where [] := {
  noir_def as_<>(self: u16) -> u16 := {
    self
  };
}

noir_trait_impl[std.impl_391]<> std::convert::AsPrimitive< i16> for u16 where [] := {
  noir_def as_<>(self: u16) -> i16 := {
    (#_cast returning i16)(self)
  };
}

noir_trait_impl[std.impl_361]<> std::convert::AsPrimitive<u64> for u16 where [] := {
  noir_def as_<>(self: u16) -> u64 := {
    (#_cast returning u64)(self)
  };
}

noir_trait_impl[std.impl_411]<> std::convert::AsPrimitive< i64> for u16 where [] := {
  noir_def as_<>(self: u16) -> i64 := {
    (#_cast returning i64)(self)
  };
}

noir_trait_impl[std.impl_331]<> std::convert::AsPrimitive<u8> for u16 where [] := {
  noir_def as_<>(self: u16) -> u8 := {
    (#_cast returning u8)(self)
  };
}

noir_trait_impl[std.impl_381]<> std::convert::AsPrimitive< i8> for u16 where [] := {
  noir_def as_<>(self: u16) -> i8 := {
    (#_cast returning i8)(self)
  };
}

noir_trait_impl[std.impl_352]<> std::convert::AsPrimitive<u32> for u32 where [] := {
  noir_def as_<>(self: u32) -> u32 := {
    self
  };
}

noir_trait_impl[std.impl_402]<> std::convert::AsPrimitive< i32> for u32 where [] := {
  noir_def as_<>(self: u32) -> i32 := {
    (#_cast returning i32)(self)
  };
}

noir_trait_impl[std.impl_322]<> std::convert::AsPrimitive<bool> for u32 where [] := {
  noir_def as_<>(self: u32) -> bool := {
    (#_uNeq returning bool)(self, (0: u32))
  };
}

noir_trait_impl[std.impl_372]<> std::convert::AsPrimitive<u128> for u32 where [] := {
  noir_def as_<>(self: u32) -> u128 := {
    (#_cast returning u128)(self)
  };
}

noir_trait_impl[std.impl_342]<> std::convert::AsPrimitive<u16> for u32 where [] := {
  noir_def as_<>(self: u32) -> u16 := {
    (#_cast returning u16)(self)
  };
}

noir_trait_impl[std.impl_392]<> std::convert::AsPrimitive< i16> for u32 where [] := {
  noir_def as_<>(self: u32) -> i16 := {
    (#_cast returning i16)(self)
  };
}

noir_trait_impl[std.impl_362]<> std::convert::AsPrimitive<u64> for u32 where [] := {
  noir_def as_<>(self: u32) -> u64 := {
    (#_cast returning u64)(self)
  };
}

noir_trait_impl[std.impl_412]<> std::convert::AsPrimitive< i64> for u32 where [] := {
  noir_def as_<>(self: u32) -> i64 := {
    (#_cast returning i64)(self)
  };
}

noir_trait_impl[std.impl_332]<> std::convert::AsPrimitive<u8> for u32 where [] := {
  noir_def as_<>(self: u32) -> u8 := {
    (#_cast returning u8)(self)
  };
}

noir_trait_impl[std.impl_382]<> std::convert::AsPrimitive< i8> for u32 where [] := {
  noir_def as_<>(self: u32) -> i8 := {
    (#_cast returning i8)(self)
  };
}

noir_trait_impl[std.impl_323]<> std::convert::AsPrimitive<bool> for u64 where [] := {
  noir_def as_<>(self: u64) -> bool := {
    (#_uNeq returning bool)(self, (0: u64))
  };
}

noir_trait_impl[std.impl_373]<> std::convert::AsPrimitive<u128> for u64 where [] := {
  noir_def as_<>(self: u64) -> u128 := {
    (#_cast returning u128)(self)
  };
}

noir_trait_impl[std.impl_343]<> std::convert::AsPrimitive<u16> for u64 where [] := {
  noir_def as_<>(self: u64) -> u16 := {
    (#_cast returning u16)(self)
  };
}

noir_trait_impl[std.impl_393]<> std::convert::AsPrimitive< i16> for u64 where [] := {
  noir_def as_<>(self: u64) -> i16 := {
    (#_cast returning i16)(self)
  };
}

noir_trait_impl[std.impl_363]<> std::convert::AsPrimitive<u64> for u64 where [] := {
  noir_def as_<>(self: u64) -> u64 := {
    self
  };
}

noir_trait_impl[std.impl_413]<> std::convert::AsPrimitive< i64> for u64 where [] := {
  noir_def as_<>(self: u64) -> i64 := {
    (#_cast returning i64)(self)
  };
}

noir_trait_impl[std.impl_333]<> std::convert::AsPrimitive<u8> for u64 where [] := {
  noir_def as_<>(self: u64) -> u8 := {
    (#_cast returning u8)(self)
  };
}

noir_trait_impl[std.impl_383]<> std::convert::AsPrimitive< i8> for u64 where [] := {
  noir_def as_<>(self: u64) -> i8 := {
    (#_cast returning i8)(self)
  };
}

noir_trait_impl[std.impl_353]<> std::convert::AsPrimitive<u32> for u64 where [] := {
  noir_def as_<>(self: u64) -> u32 := {
    (#_cast returning u32)(self)
  };
}

noir_trait_impl[std.impl_403]<> std::convert::AsPrimitive< i32> for u64 where [] := {
  noir_def as_<>(self: u64) -> i32 := {
    (#_cast returning i32)(self)
  };
}

noir_trait_impl[std.impl_324]<> std::convert::AsPrimitive<bool> for u128 where [] := {
  noir_def as_<>(self: u128) -> bool := {
    (#_uNeq returning bool)(self, (0: u128))
  };
}

noir_trait_impl[std.impl_374]<> std::convert::AsPrimitive<u128> for u128 where [] := {
  noir_def as_<>(self: u128) -> u128 := {
    self
  };
}

noir_trait_impl[std.impl_344]<> std::convert::AsPrimitive<u16> for u128 where [] := {
  noir_def as_<>(self: u128) -> u16 := {
    (#_cast returning u16)(self)
  };
}

noir_trait_impl[std.impl_394]<> std::convert::AsPrimitive< i16> for u128 where [] := {
  noir_def as_<>(self: u128) -> i16 := {
    (#_cast returning i16)(self)
  };
}

noir_trait_impl[std.impl_364]<> std::convert::AsPrimitive<u64> for u128 where [] := {
  noir_def as_<>(self: u128) -> u64 := {
    (#_cast returning u64)(self)
  };
}

noir_trait_impl[std.impl_414]<> std::convert::AsPrimitive< i64> for u128 where [] := {
  noir_def as_<>(self: u128) -> i64 := {
    (#_cast returning i64)(self)
  };
}

noir_trait_impl[std.impl_334]<> std::convert::AsPrimitive<u8> for u128 where [] := {
  noir_def as_<>(self: u128) -> u8 := {
    (#_cast returning u8)(self)
  };
}

noir_trait_impl[std.impl_384]<> std::convert::AsPrimitive< i8> for u128 where [] := {
  noir_def as_<>(self: u128) -> i8 := {
    (#_cast returning i8)(self)
  };
}

noir_trait_impl[std.impl_354]<> std::convert::AsPrimitive<u32> for u128 where [] := {
  noir_def as_<>(self: u128) -> u32 := {
    (#_cast returning u32)(self)
  };
}

noir_trait_impl[std.impl_404]<> std::convert::AsPrimitive< i32> for u128 where [] := {
  noir_def as_<>(self: u128) -> i32 := {
    (#_cast returning i32)(self)
  };
}

noir_trait_impl[std.impl_325]<> std::convert::AsPrimitive<bool> for i8 where [] := {
  noir_def as_<>(self: i8) -> bool := {
    (#_iNeq returning bool)(self, (0: i8))
  };
}

noir_trait_impl[std.impl_375]<> std::convert::AsPrimitive<u128> for i8 where [] := {
  noir_def as_<>(self: i8) -> u128 := {
    (#_cast returning u128)(self)
  };
}

noir_trait_impl[std.impl_345]<> std::convert::AsPrimitive<u16> for i8 where [] := {
  noir_def as_<>(self: i8) -> u16 := {
    (#_cast returning u16)(self)
  };
}

noir_trait_impl[std.impl_395]<> std::convert::AsPrimitive< i16> for i8 where [] := {
  noir_def as_<>(self: i8) -> i16 := {
    (#_cast returning i16)(self)
  };
}

noir_trait_impl[std.impl_365]<> std::convert::AsPrimitive<u64> for i8 where [] := {
  noir_def as_<>(self: i8) -> u64 := {
    (#_cast returning u64)(self)
  };
}

noir_trait_impl[std.impl_415]<> std::convert::AsPrimitive< i64> for i8 where [] := {
  noir_def as_<>(self: i8) -> i64 := {
    (#_cast returning i64)(self)
  };
}

noir_trait_impl[std.impl_335]<> std::convert::AsPrimitive<u8> for i8 where [] := {
  noir_def as_<>(self: i8) -> u8 := {
    (#_cast returning u8)(self)
  };
}

noir_trait_impl[std.impl_385]<> std::convert::AsPrimitive< i8> for i8 where [] := {
  noir_def as_<>(self: i8) -> i8 := {
    self
  };
}

noir_trait_impl[std.impl_355]<> std::convert::AsPrimitive<u32> for i8 where [] := {
  noir_def as_<>(self: i8) -> u32 := {
    (#_cast returning u32)(self)
  };
}

noir_trait_impl[std.impl_405]<> std::convert::AsPrimitive< i32> for i8 where [] := {
  noir_def as_<>(self: i8) -> i32 := {
    (#_cast returning i32)(self)
  };
}

noir_trait_impl[std.impl_326]<> std::convert::AsPrimitive<bool> for i16 where [] := {
  noir_def as_<>(self: i16) -> bool := {
    (#_iNeq returning bool)(self, (0: i16))
  };
}

noir_trait_impl[std.impl_376]<> std::convert::AsPrimitive<u128> for i16 where [] := {
  noir_def as_<>(self: i16) -> u128 := {
    (#_cast returning u128)(self)
  };
}

noir_trait_impl[std.impl_346]<> std::convert::AsPrimitive<u16> for i16 where [] := {
  noir_def as_<>(self: i16) -> u16 := {
    (#_cast returning u16)(self)
  };
}

noir_trait_impl[std.impl_396]<> std::convert::AsPrimitive< i16> for i16 where [] := {
  noir_def as_<>(self: i16) -> i16 := {
    self
  };
}

noir_trait_impl[std.impl_366]<> std::convert::AsPrimitive<u64> for i16 where [] := {
  noir_def as_<>(self: i16) -> u64 := {
    (#_cast returning u64)(self)
  };
}

noir_trait_impl[std.impl_416]<> std::convert::AsPrimitive< i64> for i16 where [] := {
  noir_def as_<>(self: i16) -> i64 := {
    (#_cast returning i64)(self)
  };
}

noir_trait_impl[std.impl_336]<> std::convert::AsPrimitive<u8> for i16 where [] := {
  noir_def as_<>(self: i16) -> u8 := {
    (#_cast returning u8)(self)
  };
}

noir_trait_impl[std.impl_386]<> std::convert::AsPrimitive< i8> for i16 where [] := {
  noir_def as_<>(self: i16) -> i8 := {
    (#_cast returning i8)(self)
  };
}

noir_trait_impl[std.impl_356]<> std::convert::AsPrimitive<u32> for i16 where [] := {
  noir_def as_<>(self: i16) -> u32 := {
    (#_cast returning u32)(self)
  };
}

noir_trait_impl[std.impl_406]<> std::convert::AsPrimitive< i32> for i16 where [] := {
  noir_def as_<>(self: i16) -> i32 := {
    (#_cast returning i32)(self)
  };
}

noir_trait_impl[std.impl_327]<> std::convert::AsPrimitive<bool> for i32 where [] := {
  noir_def as_<>(self: i32) -> bool := {
    (#_iNeq returning bool)(self, (0: i32))
  };
}

noir_trait_impl[std.impl_377]<> std::convert::AsPrimitive<u128> for i32 where [] := {
  noir_def as_<>(self: i32) -> u128 := {
    (#_cast returning u128)(self)
  };
}

noir_trait_impl[std.impl_347]<> std::convert::AsPrimitive<u16> for i32 where [] := {
  noir_def as_<>(self: i32) -> u16 := {
    (#_cast returning u16)(self)
  };
}

noir_trait_impl[std.impl_397]<> std::convert::AsPrimitive< i16> for i32 where [] := {
  noir_def as_<>(self: i32) -> i16 := {
    (#_cast returning i16)(self)
  };
}

noir_trait_impl[std.impl_367]<> std::convert::AsPrimitive<u64> for i32 where [] := {
  noir_def as_<>(self: i32) -> u64 := {
    (#_cast returning u64)(self)
  };
}

noir_trait_impl[std.impl_417]<> std::convert::AsPrimitive< i64> for i32 where [] := {
  noir_def as_<>(self: i32) -> i64 := {
    (#_cast returning i64)(self)
  };
}

noir_trait_impl[std.impl_337]<> std::convert::AsPrimitive<u8> for i32 where [] := {
  noir_def as_<>(self: i32) -> u8 := {
    (#_cast returning u8)(self)
  };
}

noir_trait_impl[std.impl_387]<> std::convert::AsPrimitive< i8> for i32 where [] := {
  noir_def as_<>(self: i32) -> i8 := {
    (#_cast returning i8)(self)
  };
}

noir_trait_impl[std.impl_357]<> std::convert::AsPrimitive<u32> for i32 where [] := {
  noir_def as_<>(self: i32) -> u32 := {
    (#_cast returning u32)(self)
  };
}

noir_trait_impl[std.impl_407]<> std::convert::AsPrimitive< i32> for i32 where [] := {
  noir_def as_<>(self: i32) -> i32 := {
    self
  };
}

noir_trait_impl[std.impl_348]<> std::convert::AsPrimitive<u16> for i64 where [] := {
  noir_def as_<>(self: i64) -> u16 := {
    (#_cast returning u16)(self)
  };
}

noir_trait_impl[std.impl_398]<> std::convert::AsPrimitive< i16> for i64 where [] := {
  noir_def as_<>(self: i64) -> i16 := {
    (#_cast returning i16)(self)
  };
}

noir_trait_impl[std.impl_368]<> std::convert::AsPrimitive<u64> for i64 where [] := {
  noir_def as_<>(self: i64) -> u64 := {
    (#_cast returning u64)(self)
  };
}

noir_trait_impl[std.impl_418]<> std::convert::AsPrimitive< i64> for i64 where [] := {
  noir_def as_<>(self: i64) -> i64 := {
    self
  };
}

noir_trait_impl[std.impl_338]<> std::convert::AsPrimitive<u8> for i64 where [] := {
  noir_def as_<>(self: i64) -> u8 := {
    (#_cast returning u8)(self)
  };
}

noir_trait_impl[std.impl_388]<> std::convert::AsPrimitive< i8> for i64 where [] := {
  noir_def as_<>(self: i64) -> i8 := {
    (#_cast returning i8)(self)
  };
}

noir_trait_impl[std.impl_358]<> std::convert::AsPrimitive<u32> for i64 where [] := {
  noir_def as_<>(self: i64) -> u32 := {
    (#_cast returning u32)(self)
  };
}

noir_trait_impl[std.impl_408]<> std::convert::AsPrimitive< i32> for i64 where [] := {
  noir_def as_<>(self: i64) -> i32 := {
    (#_cast returning i32)(self)
  };
}

noir_trait_impl[std.impl_328]<> std::convert::AsPrimitive<bool> for i64 where [] := {
  noir_def as_<>(self: i64) -> bool := {
    (#_iNeq returning bool)(self, (0: i64))
  };
}

noir_trait_impl[std.impl_378]<> std::convert::AsPrimitive<u128> for i64 where [] := {
  noir_def as_<>(self: i64) -> u128 := {
    (#_cast returning u128)(self)
  };
}

noir_trait_impl[std.impl_419]<> std::convert::AsPrimitive<Field> for bool where [] := {
  noir_def as_<>(self: bool) -> Field := {
    (#_cast returning Field)(self)
  };
}

noir_trait_impl[std.impl_420]<> std::convert::AsPrimitive<Field> for u8 where [] := {
  noir_def as_<>(self: u8) -> Field := {
    (#_cast returning Field)(self)
  };
}

noir_trait_impl[std.impl_421]<> std::convert::AsPrimitive<Field> for u16 where [] := {
  noir_def as_<>(self: u16) -> Field := {
    (#_cast returning Field)(self)
  };
}

noir_trait_impl[std.impl_422]<> std::convert::AsPrimitive<Field> for u32 where [] := {
  noir_def as_<>(self: u32) -> Field := {
    (#_cast returning Field)(self)
  };
}

noir_trait_impl[std.impl_423]<> std::convert::AsPrimitive<Field> for u64 where [] := {
  noir_def as_<>(self: u64) -> Field := {
    (#_cast returning Field)(self)
  };
}

noir_trait_impl[std.impl_424]<> std::convert::AsPrimitive<Field> for u128 where [] := {
  noir_def as_<>(self: u128) -> Field := {
    (#_cast returning Field)(self)
  };
}

noir_trait_impl[std.impl_427]<> std::convert::AsPrimitive<u16> for Field where [] := {
  noir_def as_<>(self: Field) -> u16 := {
    (#_cast returning u16)(self)
  };
}

noir_trait_impl[std.impl_426]<> std::convert::AsPrimitive<u8> for Field where [] := {
  noir_def as_<>(self: Field) -> u8 := {
    (#_cast returning u8)(self)
  };
}

noir_trait_impl[std.impl_425]<> std::convert::AsPrimitive<bool> for Field where [] := {
  noir_def as_<>(self: Field) -> bool := {
    (#_fNeq returning bool)(self, (0: Field))
  };
}

noir_trait_impl[std.impl_430]<> std::convert::AsPrimitive<u128> for Field where [] := {
  noir_def as_<>(self: Field) -> u128 := {
    (#_cast returning u128)(self)
  };
}

noir_trait_impl[std.impl_429]<> std::convert::AsPrimitive<u64> for Field where [] := {
  noir_def as_<>(self: Field) -> u64 := {
    (#_cast returning u64)(self)
  };
}

noir_trait_impl[std.impl_428]<> std::convert::AsPrimitive<u32> for Field where [] := {
  noir_def as_<>(self: Field) -> u32 := {
    (#_cast returning u32)(self)
  };
}

def std.Convert.env : Env := Env.mk
  []
  [std.impl_40, std.impl_41, std.impl_42, std.impl_43, std.impl_44, std.impl_45, std.impl_46, std.impl_47, std.impl_48, std.impl_49, std.impl_50, std.impl_51, std.impl_52, std.impl_53, std.impl_54, std.impl_55, std.impl_56, std.impl_57, std.impl_58, std.impl_59, std.impl_60, std.impl_61, std.impl_62, std.impl_63, std.impl_64, std.impl_65, std.impl_66, std.impl_67, std.impl_68, std.impl_69, std.impl_70, std.impl_71, std.impl_72, std.impl_349, std.impl_399, std.impl_319, std.impl_369, std.impl_339, std.impl_389, std.impl_359, std.impl_409, std.impl_329, std.impl_379, std.impl_350, std.impl_400, std.impl_320, std.impl_370, std.impl_340, std.impl_390, std.impl_360, std.impl_410, std.impl_330, std.impl_380, std.impl_351, std.impl_401, std.impl_321, std.impl_371, std.impl_341, std.impl_391, std.impl_361, std.impl_411, std.impl_331, std.impl_381, std.impl_352, std.impl_402, std.impl_322, std.impl_372, std.impl_342, std.impl_392, std.impl_362, std.impl_412, std.impl_332, std.impl_382, std.impl_323, std.impl_373, std.impl_343, std.impl_393, std.impl_363, std.impl_413, std.impl_333, std.impl_383, std.impl_353, std.impl_403, std.impl_324, std.impl_374, std.impl_344, std.impl_394, std.impl_364, std.impl_414, std.impl_334, std.impl_384, std.impl_354, std.impl_404, std.impl_325, std.impl_375, std.impl_345, std.impl_395, std.impl_365, std.impl_415, std.impl_335, std.impl_385, std.impl_355, std.impl_405, std.impl_326, std.impl_376, std.impl_346, std.impl_396, std.impl_366, std.impl_416, std.impl_336, std.impl_386, std.impl_356, std.impl_406, std.impl_327, std.impl_377, std.impl_347, std.impl_397, std.impl_367, std.impl_417, std.impl_337, std.impl_387, std.impl_357, std.impl_407, std.impl_348, std.impl_398, std.impl_368, std.impl_418, std.impl_338, std.impl_388, std.impl_358, std.impl_408, std.impl_328, std.impl_378, std.impl_419, std.impl_420, std.impl_421, std.impl_422, std.impl_423, std.impl_424, std.impl_427, std.impl_426, std.impl_425, std.impl_430, std.impl_429, std.impl_428]
