-- Generated by lampe

import std.Extracted.GeneratedTypes
import Lampe

open Lampe

set_option linter.unusedVariables false

noir_trait_impl[std.impl_272]<> std::default::Default<> for Field where [] := {
  noir_def default<>() -> Field := {
    (0: Field)
  };
}

noir_trait_impl[std.impl_273]<> std::default::Default<> for u1 where [] := {
  noir_def default<>() -> u1 := {
    (0: u1)
  };
}

noir_trait_impl[std.impl_274]<> std::default::Default<> for u8 where [] := {
  noir_def default<>() -> u8 := {
    (0: u8)
  };
}

noir_trait_impl[std.impl_275]<> std::default::Default<> for u16 where [] := {
  noir_def default<>() -> u16 := {
    (0: u16)
  };
}

noir_trait_impl[std.impl_276]<> std::default::Default<> for u32 where [] := {
  noir_def default<>() -> u32 := {
    (0: u32)
  };
}

noir_trait_impl[std.impl_277]<> std::default::Default<> for u64 where [] := {
  noir_def default<>() -> u64 := {
    (0: u64)
  };
}

noir_trait_impl[std.impl_278]<> std::default::Default<> for u128 where [] := {
  noir_def default<>() -> u128 := {
    (0: u128)
  };
}

noir_trait_impl[std.impl_279]<> std::default::Default<> for i8 where [] := {
  noir_def default<>() -> i8 := {
    (0: i8)
  };
}

noir_trait_impl[std.impl_280]<> std::default::Default<> for i16 where [] := {
  noir_def default<>() -> i16 := {
    (0: i16)
  };
}

noir_trait_impl[std.impl_281]<> std::default::Default<> for i32 where [] := {
  noir_def default<>() -> i32 := {
    (0: i32)
  };
}

noir_trait_impl[std.impl_282]<> std::default::Default<> for i64 where [] := {
  noir_def default<>() -> i64 := {
    (0: i64)
  };
}

noir_trait_impl[std.impl_283]<> std::default::Default<> for Unit where [] := {
  noir_def default<>() -> Unit := {
    #_unit
  };
}

noir_trait_impl[std.impl_284]<> std::default::Default<> for bool where [] := {
  noir_def default<>() -> bool := {
    #_false
  };
}

noir_trait_impl[std.impl_285]<N: u32, T: Type> std::default::Default<> for Array<T, N: u32> where [T: std::default::Default<>] := {
  noir_def default<>() -> Array<T, N: u32> := {
    (#_mkRepeatedArray returning Array<T, N: u32>)(((T as std::default::Default<>)::default<> as λ() -> T)())
  };
}

noir_trait_impl[std.impl_286]<T: Type> std::default::Default<> for Vector<T> where [] := {
  noir_def default<>() -> Vector<T> := {
    (#_asVector returning Vector<T>)((#_mkArray returning Array<T, 0: u32>)())
  };
}

noir_trait_impl[std.impl_287]<A: Type, B: Type> std::default::Default<> for Tuple<A, B> where [A: std::default::Default<>, B: std::default::Default<>] := {
  noir_def default<>() -> Tuple<A, B> := {
    (#_makeData returning Tuple<A, B>)(((A as std::default::Default<>)::default<> as λ() -> A)(), ((B as std::default::Default<>)::default<> as λ() -> B)())
  };
}

noir_trait_impl[std.impl_288]<A: Type, B: Type, C: Type> std::default::Default<> for Tuple<A, B, C> where [A: std::default::Default<>, B: std::default::Default<>, C: std::default::Default<>] := {
  noir_def default<>() -> Tuple<A, B, C> := {
    (#_makeData returning Tuple<A, B, C>)(((A as std::default::Default<>)::default<> as λ() -> A)(), ((B as std::default::Default<>)::default<> as λ() -> B)(), ((C as std::default::Default<>)::default<> as λ() -> C)())
  };
}

noir_trait_impl[std.impl_289]<A: Type, B: Type, C: Type, D: Type> std::default::Default<> for Tuple<A, B, C, D> where [A: std::default::Default<>, B: std::default::Default<>, C: std::default::Default<>, D: std::default::Default<>] := {
  noir_def default<>() -> Tuple<A, B, C, D> := {
    (#_makeData returning Tuple<A, B, C, D>)(((A as std::default::Default<>)::default<> as λ() -> A)(), ((B as std::default::Default<>)::default<> as λ() -> B)(), ((C as std::default::Default<>)::default<> as λ() -> C)(), ((D as std::default::Default<>)::default<> as λ() -> D)())
  };
}

noir_trait_impl[std.impl_290]<A: Type, B: Type, C: Type, D: Type, E: Type> std::default::Default<> for Tuple<A, B, C, D, E> where [A: std::default::Default<>, B: std::default::Default<>, C: std::default::Default<>, D: std::default::Default<>, E: std::default::Default<>] := {
  noir_def default<>() -> Tuple<A, B, C, D, E> := {
    (#_makeData returning Tuple<A, B, C, D, E>)(((A as std::default::Default<>)::default<> as λ() -> A)(), ((B as std::default::Default<>)::default<> as λ() -> B)(), ((C as std::default::Default<>)::default<> as λ() -> C)(), ((D as std::default::Default<>)::default<> as λ() -> D)(), ((E as std::default::Default<>)::default<> as λ() -> E)())
  };
}

def std.Default.env : Env := Env.mk
  []
  [std.impl_272, std.impl_273, std.impl_274, std.impl_275, std.impl_276, std.impl_277, std.impl_278, std.impl_279, std.impl_280, std.impl_281, std.impl_282, std.impl_283, std.impl_284, std.impl_285, std.impl_286, std.impl_287, std.impl_288, std.impl_289, std.impl_290]
