-- Generated by lampe

import std.Extracted.GeneratedTypes
import Lampe

open Lampe

set_option linter.unusedVariables false

noir_def std::ecdsa_secp256r1::verify_signature<>(public_key_x: Array<u8, 32: u32>, public_key_y: Array<u8, 32: u32>, signature: Array<u8, 64: u32>, message_hash: Array<u8, 32: u32>) -> bool := {
  (#_ecdsaSecp256R1 returning bool)(public_key_x, public_key_y, signature, message_hash, #_true)
}

def std.EcdsaSecp256R1.env : Env := Env.mk
  [«std::ecdsa_secp256r1::verify_signature»]
  []
