-- Generated by lampe

import std.Extracted.GeneratedTypes
import Lampe

open Lampe

set_option linter.unusedVariables false

noir_def std::print_oracle<T: Type>(with_newline: bool, input: T) -> Unit := {
  (#_fresh returning Unit)()
}

noir_def std::print_unconstrained<T: Type>(with_newline: bool, input: T) -> Unit := {
  (#_fresh returning Unit)()
}

noir_def std::println<T: Type>(input: T) -> Unit := {
  (std::print_unconstrained<T> as λ(bool, T) -> Unit)(#_true, input);
  #_skip
}

noir_def std::print<T: Type>(input: T) -> Unit := {
  (std::print_unconstrained<T> as λ(bool, T) -> Unit)(#_false, input);
  #_skip
}

noir_def std::verify_proof_with_type<N: u32, M: u32, K: u32>(verification_key: Array<Field, N: u32>, proof: Array<Field, M: u32>, public_inputs: Array<Field, K: u32>, key_hash: Field, proof_type: u32) -> Unit := {
  if (#_bNot returning bool)((#_isUnconstrained returning bool)()) then {
    (#_assertConstant returning Unit)(proof_type);
    #_skip
  };
  (#_recursiveAggregation returning Unit)(verification_key, proof, public_inputs, key_hash, proof_type);
  #_skip
}

def std.Lib.env : Env := Env.mk
  [«std::print_oracle», «std::print_unconstrained», «std::println», «std::print», «std::verify_proof_with_type»]
  []
