-- Generated by lampe

import std.Extracted.GeneratedTypes
import Lampe

open Lampe

set_option linter.unusedVariables false

noir_def std::panic::panic<T: Type, U: Type>(message: T) -> U := {
  (#_assert returning Unit)(#_false);
  (#_zeroed returning U)()
}

noir_trait_impl[std.impl_317]<N: u32> std::panic::StringLike<> for String<N: u32> where [] := {
}

noir_trait_impl[std.impl_318]<N: u32, T: Type> std::panic::StringLike<> for FmtString<N: u32, T> where [] := {
}

def std.Panic.env : Env := Env.mk
  [«std::panic::panic»]
  [std.impl_317, std.impl_318]
