-- Generated by lampe

import std.Extracted.GeneratedTypes
import Lampe

open Lampe

set_option linter.unusedVariables false

noir_def std::string::as_bytes_vec<N: u32>(self: String<N: u32>) -> Vector<u8> := {
  (#_asVector returning Vector<u8>)((#_strAsBytes returning Array<u8, N: u32>)(self))
}

noir_trait_impl[std.impl_77]<N: u32> std::convert::From<Array<u8, N: u32> > for String<N: u32> where [] := {
  noir_def «from»<>(bytes: Array<u8, N: u32>) -> String<N: u32> := {
    (#_arrayAsStrUnchecked returning String<N: u32>)(bytes)
  };
}

def std.String.env : Env := Env.mk
  [«std::string::as_bytes_vec»]
  [std.impl_77]
