-- Generated by lampe

import «skyscraper-0.0.0».Extracted.Bar
import «skyscraper-0.0.0».Extracted.Components
import «skyscraper-0.0.0».Extracted.GeneratedTypes
import «skyscraper-0.0.0».Extracted.Globals
import «skyscraper-0.0.0».Extracted.Lib
import «skyscraper-0.0.0».Extracted.Permute
import «hasher-0.0.0».Extracted
import std.Extracted

namespace «skyscraper-0.0.0»

def env := Bar.env
  ++ Components.env
  ++ Globals.env
  ++ Lib.env
  ++ Permute.env
  ++ «hasher-0.0.0».env
  ++ std.env
