-- Generated by lampe

import std.Extracted.GeneratedTypes
import Lampe

open Lampe

set_option linter.unusedVariables false

noir_trait_impl[std.impl_292]<N: u32> std::«meta»::ctstring::AsCtString<> for String<N: u32> where [] := {
  noir_def as_ctstring<>(self: String<N: u32>) -> Unit := {
    (#_strAsCtstring returning Unit)(self)
  };
}

noir_trait_impl[std.impl_293]<N: u32, T: Type> std::«meta»::ctstring::AsCtString<> for FmtString<N: u32, T> where [] := {
  noir_def as_ctstring<>(self: FmtString<N: u32, T>) -> Unit := {
    (#_fmtstrAsCtstring returning Unit)(self)
  };
}

noir_def std::«meta»::ctstring::test::as_quoted_str_example<>() -> Unit := {
  #_unit
}

def std.Meta.Ctstring.env : Env := Env.mk
  [«std::meta::ctstring::test::as_quoted_str_example»]
  [std.impl_292, std.impl_293]
