-- Generated by lampe

import std.Extracted.GeneratedTypes
import Lampe

open Lampe

set_option linter.unusedVariables false

noir_def std::«meta»::tests::returning_versus_macro_insertion<>() -> Unit := {
  #_unit
}

noir_trait_impl[std.impl_431]<> std::«meta»::tests::FieldCount<> for std::«meta»::tests::Bar<> where [] := {
  noir_def field_count<>() -> u32 := {
    (2: u32)
  };
}

noir_trait_impl[std.impl_314]<> std::«meta»::tests::DoNothing<> for std::«meta»::tests::Bar<> where [] := {
  noir_def do_nothing<>(__0: std::«meta»::tests::Bar<>) -> Unit := {
    #_skip
  };
}

noir_def std::«meta»::tests::concatenate_test<>() -> Unit := {
  #_unit
}

noir_def std::«meta»::tests::remove_unused_warnings<>() -> Unit := {
  let __0 = (#_makeData returning std::«meta»::tests::Bar<>)((1: Field), (#_mkArray returning Array<Field, 2: u32>)((2: Field), (3: Field)));
  let __1 = (#_makeData returning std::«meta»::tests::MyStruct<>)((1: i32));
  let __3 = (#_makeData returning std::«meta»::tests::MyOtherStruct<>)((2: u32));
  let __7 = (std::«meta»::tests::derive_do_nothing<> as λ(Unit) -> Unit)((std::panic::panic<String<0: u32>, Unit> as λ(String<0: u32>) -> Unit)(""));
  let __15 = (std::«meta»::tests::derive_do_nothing_alt<> as λ(Unit) -> Unit)((std::panic::panic<String<0: u32>, Unit> as λ(String<0: u32>) -> Unit)(""));
  if #_false then {
    (std::«meta»::tests::remove_unused_warnings<> as λ() -> Unit)();
    #_skip
  }
}

def std.Meta.Mod.env : Env := Env.mk
  [«std::meta::tests::returning_versus_macro_insertion», «std::meta::tests::concatenate_test», «std::meta::tests::remove_unused_warnings»]
  [std.impl_431, std.impl_314]
