-- Generated by lampe

import std.Extracted.GeneratedTypes
import Lampe

open Lampe

set_option linter.unusedVariables false

noir_global_def std::collections::map::MAX_LOAD_FACTOR_NUMERATOR: u32 = (3: u32);

noir_global_def std::collections::map::MAX_LOAD_FACTOR_DENOMINATOR: u32 = (4: u32);

noir_trait_impl[std.impl_34]<K: Type, V: Type> std::default::Default<> for std::collections::map::Slot<K, V> where [] := {
  noir_def default<>() -> std::collections::map::Slot<K, V> := {
    (#_makeData returning std::collections::map::Slot<K, V>)((#_zeroed returning K)(), (#_zeroed returning V)(), #_false, #_false)
  };
}

noir_def std::collections::map::Slot::is_valid<K: Type, V: Type>(self: std::collections::map::Slot<K, V>) -> bool := {
  (#_bAnd returning bool)((#_bNot returning bool)(self.3), self.2)
}

noir_def std::collections::map::Slot::is_available<K: Type, V: Type>(self: std::collections::map::Slot<K, V>) -> bool := {
  (#_bOr returning bool)(self.3, (#_bNot returning bool)(self.2))
}

noir_def std::collections::map::Slot::set<K: Type, V: Type>(self: & std::collections::map::Slot<K, V>, key: K, value: V) -> Unit := {
  ((*self: std::collections::map::Slot<K, V>).0: K) = key;
  ((*self: std::collections::map::Slot<K, V>).1: V) = value;
  ((*self: std::collections::map::Slot<K, V>).2: bool) = #_true;
  ((*self: std::collections::map::Slot<K, V>).3: bool) = #_false;
  #_skip
}

noir_def std::collections::map::Slot::mark_deleted<K: Type, V: Type>(self: & std::collections::map::Slot<K, V>) -> Unit := {
  ((*self: std::collections::map::Slot<K, V>).3: bool) = #_true;
  #_skip
}

noir_def std::collections::map::HashMap::with_hasher<K: Type, V: Type, N: u32, B: Type, B_as_BuildHasher_H: Type>(_build_hasher: B) -> std::collections::map::HashMap<K, V, N: u32, B> := {
  let _table = (#_mkRepeatedArray returning Array<std::collections::map::Slot<K, V>, N: u32>)(((std::collections::map::Slot<K, V> as std::default::Default<>)::default<> as λ() -> std::collections::map::Slot<K, V>)());
  let _len = (0: u32);
  (#_makeData returning std::collections::map::HashMap<K, V, N: u32, B>)(_table, _len, _build_hasher)
}

noir_def std::collections::map::HashMap::clear<K: Type, V: Type, N: u32, B: Type>(self: & std::collections::map::HashMap<K, V, N: u32, B>) -> Unit := {
  ((*self: std::collections::map::HashMap<K, V, N: u32, B>).0: Array<std::collections::map::Slot<K, V>, N: u32>) = (#_mkRepeatedArray returning Array<std::collections::map::Slot<K, V>, N: u32>)(((std::collections::map::Slot<K, V> as std::default::Default<>)::default<> as λ() -> std::collections::map::Slot<K, V>)());
  ((*self: std::collections::map::HashMap<K, V, N: u32, B>).1: u32) = (0: u32);
  #_skip
}

noir_def std::collections::map::HashMap::contains_key<K: Type, V: Type, N: u32, B: Type, B_as_BuildHasher_H: Type>(self: std::collections::map::HashMap<K, V, N: u32, B>, key: K) -> bool := {
  (std::option::Option::is_some<V> as λ(std::option::Option<V>) -> bool)((std::collections::map::HashMap::get<K, V, N: u32, B, B_as_BuildHasher_H> as λ(std::collections::map::HashMap<K, V, N: u32, B>, K) -> std::option::Option<V>)(self, key))
}

noir_def std::collections::map::HashMap::is_empty<K: Type, V: Type, N: u32, B: Type>(self: std::collections::map::HashMap<K, V, N: u32, B>) -> bool := {
  (#_uEq returning bool)(self.1, (0: u32))
}

noir_def std::collections::map::HashMap::entries<K: Type, V: Type, N: u32, B: Type>(self: std::collections::map::HashMap<K, V, N: u32, B>) -> std::collections::bounded_vec::BoundedVec<Tuple<K, V>, N: u32> := {
  let entries = (#_ref returning & std::collections::bounded_vec::BoundedVec<Tuple<K, V>, N: u32>)((std::collections::bounded_vec::BoundedVec::new<Tuple<K, V>, N: u32> as λ() -> std::collections::bounded_vec::BoundedVec<Tuple<K, V>, N: u32>)());
  {
    let ζi0 = self.0;
    for ζi1 in (0: u32) .. (#_arrayLen returning u32)(ζi0) do {
      let slot = (#_arrayIndex returning std::collections::map::Slot<K, V>)(ζi0, (#_cast returning u32)(ζi1));
      {
        if (std::collections::map::Slot::is_valid<K, V> as λ(std::collections::map::Slot<K, V>) -> bool)(slot) then {
          (std::collections::bounded_vec::BoundedVec::push<Tuple<K, V>, N: u32> as λ(& std::collections::bounded_vec::BoundedVec<Tuple<K, V>, N: u32>, Tuple<K, V>) -> Unit)(entries, (#_makeData returning Tuple<K, V>)(slot.0, slot.1));
          #_skip
        }
      }
    };
    #_skip
  };
  let self_len = self.1;
  let entries_len = (std::collections::bounded_vec::BoundedVec::len<Tuple<K, V>, N: u32> as λ(std::collections::bounded_vec::BoundedVec<Tuple<K, V>, N: u32>) -> u32)((#_readRef returning std::collections::bounded_vec::BoundedVec<Tuple<K, V>, N: u32>)(entries));
  let msg = (#_mkFormatString returning FmtString<82: u32, Tuple<u32, u32> >)("Amount of valid elements should have been {}{self_len}{} times, but got {}{entries_len}{}.", self_len, entries_len);
  (#_assert returning Unit)((#_uEq returning bool)((std::collections::bounded_vec::BoundedVec::len<Tuple<K, V>, N: u32> as λ(std::collections::bounded_vec::BoundedVec<Tuple<K, V>, N: u32>) -> u32)((#_readRef returning std::collections::bounded_vec::BoundedVec<Tuple<K, V>, N: u32>)(entries)), self.1));
  (#_readRef returning std::collections::bounded_vec::BoundedVec<Tuple<K, V>, N: u32>)(entries)
}

noir_def std::collections::map::HashMap::keys<K: Type, V: Type, N: u32, B: Type>(self: std::collections::map::HashMap<K, V, N: u32, B>) -> std::collections::bounded_vec::BoundedVec<K, N: u32> := {
  let keys = (#_ref returning & std::collections::bounded_vec::BoundedVec<K, N: u32>)((std::collections::bounded_vec::BoundedVec::new<K, N: u32> as λ() -> std::collections::bounded_vec::BoundedVec<K, N: u32>)());
  {
    let ζi0 = self.0;
    for ζi1 in (0: u32) .. (#_arrayLen returning u32)(ζi0) do {
      let slot = (#_arrayIndex returning std::collections::map::Slot<K, V>)(ζi0, (#_cast returning u32)(ζi1));
      {
        if (std::collections::map::Slot::is_valid<K, V> as λ(std::collections::map::Slot<K, V>) -> bool)(slot) then {
          (std::collections::bounded_vec::BoundedVec::push<K, N: u32> as λ(& std::collections::bounded_vec::BoundedVec<K, N: u32>, K) -> Unit)(keys, slot.0);
          #_skip
        }
      }
    };
    #_skip
  };
  let self_len = self.1;
  let keys_len = (std::collections::bounded_vec::BoundedVec::len<K, N: u32> as λ(std::collections::bounded_vec::BoundedVec<K, N: u32>) -> u32)((#_readRef returning std::collections::bounded_vec::BoundedVec<K, N: u32>)(keys));
  let msg = (#_mkFormatString returning FmtString<79: u32, Tuple<u32, u32> >)("Amount of valid elements should have been {}{self_len}{} times, but got {}{keys_len}{}.", self_len, keys_len);
  (#_assert returning Unit)((#_uEq returning bool)((std::collections::bounded_vec::BoundedVec::len<K, N: u32> as λ(std::collections::bounded_vec::BoundedVec<K, N: u32>) -> u32)((#_readRef returning std::collections::bounded_vec::BoundedVec<K, N: u32>)(keys)), self.1));
  (#_readRef returning std::collections::bounded_vec::BoundedVec<K, N: u32>)(keys)
}

noir_def std::collections::map::HashMap::values<K: Type, V: Type, N: u32, B: Type>(self: std::collections::map::HashMap<K, V, N: u32, B>) -> std::collections::bounded_vec::BoundedVec<V, N: u32> := {
  let values = (#_ref returning & std::collections::bounded_vec::BoundedVec<V, N: u32>)((std::collections::bounded_vec::BoundedVec::new<V, N: u32> as λ() -> std::collections::bounded_vec::BoundedVec<V, N: u32>)());
  {
    let ζi0 = self.0;
    for ζi1 in (0: u32) .. (#_arrayLen returning u32)(ζi0) do {
      let slot = (#_arrayIndex returning std::collections::map::Slot<K, V>)(ζi0, (#_cast returning u32)(ζi1));
      {
        if (std::collections::map::Slot::is_valid<K, V> as λ(std::collections::map::Slot<K, V>) -> bool)(slot) then {
          (std::collections::bounded_vec::BoundedVec::push<V, N: u32> as λ(& std::collections::bounded_vec::BoundedVec<V, N: u32>, V) -> Unit)(values, slot.1);
          #_skip
        }
      }
    };
    #_skip
  };
  let self_len = self.1;
  let values_len = (std::collections::bounded_vec::BoundedVec::len<V, N: u32> as λ(std::collections::bounded_vec::BoundedVec<V, N: u32>) -> u32)((#_readRef returning std::collections::bounded_vec::BoundedVec<V, N: u32>)(values));
  let msg = (#_mkFormatString returning FmtString<81: u32, Tuple<u32, u32> >)("Amount of valid elements should have been {}{self_len}{} times, but got {}{values_len}{}.", self_len, values_len);
  (#_assert returning Unit)((#_uEq returning bool)((std::collections::bounded_vec::BoundedVec::len<V, N: u32> as λ(std::collections::bounded_vec::BoundedVec<V, N: u32>) -> u32)((#_readRef returning std::collections::bounded_vec::BoundedVec<V, N: u32>)(values)), self.1));
  (#_readRef returning std::collections::bounded_vec::BoundedVec<V, N: u32>)(values)
}

noir_def std::collections::map::HashMap::iter_mut<K: Type, V: Type, N: u32, B: Type, B_as_BuildHasher_H: Type>(self: & std::collections::map::HashMap<K, V, N: u32, B>, f: λ(K, V) -> Tuple<K, V>) -> Unit := {
  let entries = (#_ref returning & std::collections::bounded_vec::BoundedVec<Tuple<K, V>, N: u32>)((std::collections::map::HashMap::entries<K, V, N: u32, B> as λ(std::collections::map::HashMap<K, V, N: u32, B>) -> std::collections::bounded_vec::BoundedVec<Tuple<K, V>, N: u32>)((#_readRef returning std::collections::map::HashMap<K, V, N: u32, B>)(self)));
  let new_map = (#_ref returning & std::collections::map::HashMap<K, V, N: u32, B>)((std::collections::map::HashMap::with_hasher<K, V, N: u32, B, B_as_BuildHasher_H> as λ(B) -> std::collections::map::HashMap<K, V, N: u32, B>)((#_readRef returning std::collections::map::HashMap<K, V, N: u32, B>)(self).2));
  for i in (0: u32) .. uConst!(N: u32) do {
    if (#_uLt returning bool)(i, (#_readRef returning std::collections::map::HashMap<K, V, N: u32, B>)(self).1) then {
      let entry = (std::collections::bounded_vec::BoundedVec::get_unchecked<Tuple<K, V>, N: u32> as λ(std::collections::bounded_vec::BoundedVec<Tuple<K, V>, N: u32>, u32) -> Tuple<K, V>)((#_readRef returning std::collections::bounded_vec::BoundedVec<Tuple<K, V>, N: u32>)(entries), i);
      let (key, value) = (f as λ(K, V) -> Tuple<K, V>)(entry.0, entry.1);
      (std::collections::map::HashMap::insert<K, V, N: u32, B, B_as_BuildHasher_H> as λ(& std::collections::map::HashMap<K, V, N: u32, B>, K, V) -> Unit)(new_map, key, value);
      #_skip
    }
  };
  ((*self: std::collections::map::HashMap<K, V, N: u32, B>).0: Array<std::collections::map::Slot<K, V>, N: u32>) = (#_readRef returning std::collections::map::HashMap<K, V, N: u32, B>)(new_map).0;
  ((*self: std::collections::map::HashMap<K, V, N: u32, B>).1: u32) = (#_readRef returning std::collections::map::HashMap<K, V, N: u32, B>)(new_map).1;
  #_skip
}

noir_def std::collections::map::HashMap::iter_keys_mut<K: Type, V: Type, N: u32, B: Type, B_as_BuildHasher_H: Type>(self: & std::collections::map::HashMap<K, V, N: u32, B>, f: λ(K) -> K) -> Unit := {
  let entries = (#_ref returning & std::collections::bounded_vec::BoundedVec<Tuple<K, V>, N: u32>)((std::collections::map::HashMap::entries<K, V, N: u32, B> as λ(std::collections::map::HashMap<K, V, N: u32, B>) -> std::collections::bounded_vec::BoundedVec<Tuple<K, V>, N: u32>)((#_readRef returning std::collections::map::HashMap<K, V, N: u32, B>)(self)));
  let new_map = (#_ref returning & std::collections::map::HashMap<K, V, N: u32, B>)((std::collections::map::HashMap::with_hasher<K, V, N: u32, B, B_as_BuildHasher_H> as λ(B) -> std::collections::map::HashMap<K, V, N: u32, B>)((#_readRef returning std::collections::map::HashMap<K, V, N: u32, B>)(self).2));
  for i in (0: u32) .. uConst!(N: u32) do {
    if (#_uLt returning bool)(i, (#_readRef returning std::collections::map::HashMap<K, V, N: u32, B>)(self).1) then {
      let entry = (std::collections::bounded_vec::BoundedVec::get_unchecked<Tuple<K, V>, N: u32> as λ(std::collections::bounded_vec::BoundedVec<Tuple<K, V>, N: u32>, u32) -> Tuple<K, V>)((#_readRef returning std::collections::bounded_vec::BoundedVec<Tuple<K, V>, N: u32>)(entries), i);
      let (key, value) = (#_makeData returning Tuple<K, V>)((f as λ(K) -> K)(entry.0), entry.1);
      (std::collections::map::HashMap::insert<K, V, N: u32, B, B_as_BuildHasher_H> as λ(& std::collections::map::HashMap<K, V, N: u32, B>, K, V) -> Unit)(new_map, key, value);
      #_skip
    }
  };
  ((*self: std::collections::map::HashMap<K, V, N: u32, B>).0: Array<std::collections::map::Slot<K, V>, N: u32>) = (#_readRef returning std::collections::map::HashMap<K, V, N: u32, B>)(new_map).0;
  ((*self: std::collections::map::HashMap<K, V, N: u32, B>).1: u32) = (#_readRef returning std::collections::map::HashMap<K, V, N: u32, B>)(new_map).1;
  #_skip
}

noir_def std::collections::map::HashMap::iter_values_mut<K: Type, V: Type, N: u32, B: Type>(self: & std::collections::map::HashMap<K, V, N: u32, B>, f: λ(V) -> V) -> Unit := {
  for i in (0: u32) .. uConst!(N: u32) do {
    let slot = (#_ref returning & std::collections::map::Slot<K, V>)((#_arrayIndex returning std::collections::map::Slot<K, V>)((#_readRef returning std::collections::map::HashMap<K, V, N: u32, B>)(self).0, (#_cast returning u32)(i)));
    if (std::collections::map::Slot::is_valid<K, V> as λ(std::collections::map::Slot<K, V>) -> bool)((#_readRef returning std::collections::map::Slot<K, V>)(slot)) then {
      (slot.1: V) = (f as λ(V) -> V)((#_readRef returning std::collections::map::Slot<K, V>)(slot).1);
      (((*self: std::collections::map::HashMap<K, V, N: u32, B>).0: Array<std::collections::map::Slot<K, V>, N: u32>)[i]: std::collections::map::Slot<K, V>) = (#_readRef returning std::collections::map::Slot<K, V>)(slot);
      #_skip
    }
  };
  #_skip
}

noir_def std::collections::map::HashMap::retain<K: Type, V: Type, N: u32, B: Type>(self: & std::collections::map::HashMap<K, V, N: u32, B>, f: λ(K, V) -> bool) -> Unit := {
  for index in (0: u32) .. uConst!(N: u32) do {
    let slot = (#_ref returning & std::collections::map::Slot<K, V>)((#_arrayIndex returning std::collections::map::Slot<K, V>)((#_readRef returning std::collections::map::HashMap<K, V, N: u32, B>)(self).0, (#_cast returning u32)(index)));
    if (std::collections::map::Slot::is_valid<K, V> as λ(std::collections::map::Slot<K, V>) -> bool)((#_readRef returning std::collections::map::Slot<K, V>)(slot)) then {
      if (#_bNot returning bool)((f as λ(K, V) -> bool)((#_readRef returning std::collections::map::Slot<K, V>)(slot).0, (#_readRef returning std::collections::map::Slot<K, V>)(slot).1)) then {
        (std::collections::map::Slot::mark_deleted<K, V> as λ(& std::collections::map::Slot<K, V>) -> Unit)(slot);
        ((*self: std::collections::map::HashMap<K, V, N: u32, B>).1: u32) = (#_uSub returning u32)((#_readRef returning std::collections::map::HashMap<K, V, N: u32, B>)(self).1, (1: u32));
        (((*self: std::collections::map::HashMap<K, V, N: u32, B>).0: Array<std::collections::map::Slot<K, V>, N: u32>)[index]: std::collections::map::Slot<K, V>) = (#_readRef returning std::collections::map::Slot<K, V>)(slot);
        #_skip
      }
    }
  };
  #_skip
}

noir_def std::collections::map::HashMap::len<K: Type, V: Type, N: u32, B: Type>(self: std::collections::map::HashMap<K, V, N: u32, B>) -> u32 := {
  self.1
}

noir_def std::collections::map::HashMap::capacity<K: Type, V: Type, N: u32, B: Type>(_self: std::collections::map::HashMap<K, V, N: u32, B>) -> u32 := {
  uConst!(N: u32)
}

noir_def std::collections::map::HashMap::get<K: Type, V: Type, N: u32, B: Type, B_as_BuildHasher_H: Type>(self: std::collections::map::HashMap<K, V, N: u32, B>, key: K) -> std::option::Option<V> := {
  let result = (#_ref returning & std::option::Option<V>)((std::option::Option::none<V> as λ() -> std::option::Option<V>)());
  let hash = (std::collections::map::HashMap::hash<K, V, N: u32, B, B_as_BuildHasher_H> as λ(std::collections::map::HashMap<K, V, N: u32, B>, K) -> u32)(self, key);
  let should_break = (#_ref returning & bool)(#_false);
  for attempt in (0: u32) .. uConst!(N: u32) do {
    if (#_bNot returning bool)((#_readRef returning bool)(should_break)) then {
      let index = (std::collections::map::HashMap::quadratic_probe<K, V, N: u32, B> as λ(std::collections::map::HashMap<K, V, N: u32, B>, u32, u32) -> u32)(self, hash, (#_cast returning u32)(attempt));
      let slot = (#_arrayIndex returning std::collections::map::Slot<K, V>)(self.0, (#_cast returning u32)(index));
      if (std::collections::map::Slot::is_valid<K, V> as λ(std::collections::map::Slot<K, V>) -> bool)(slot) then {
        if ((K as std::cmp::Eq<>)::eq<> as λ(K, K) -> bool)(slot.0, key) then {
          result = (std::option::Option::some<V> as λ(V) -> std::option::Option<V>)(slot.1);
          should_break = #_true;
          #_skip
        }
      }
    }
  };
  (#_readRef returning std::option::Option<V>)(result)
}

noir_def std::collections::map::HashMap::insert<K: Type, V: Type, N: u32, B: Type, B_as_BuildHasher_H: Type>(self: & std::collections::map::HashMap<K, V, N: u32, B>, key: K, value: V) -> Unit := {
  (std::collections::map::HashMap::assert_load_factor<K, V, N: u32, B> as λ(std::collections::map::HashMap<K, V, N: u32, B>) -> Unit)((#_readRef returning std::collections::map::HashMap<K, V, N: u32, B>)(self));
  let hash = (std::collections::map::HashMap::hash<K, V, N: u32, B, B_as_BuildHasher_H> as λ(std::collections::map::HashMap<K, V, N: u32, B>, K) -> u32)((#_readRef returning std::collections::map::HashMap<K, V, N: u32, B>)(self), key);
  let should_break = (#_ref returning & bool)(#_false);
  for attempt in (0: u32) .. uConst!(N: u32) do {
    if (#_bNot returning bool)((#_readRef returning bool)(should_break)) then {
      let index = (std::collections::map::HashMap::quadratic_probe<K, V, N: u32, B> as λ(std::collections::map::HashMap<K, V, N: u32, B>, u32, u32) -> u32)((#_readRef returning std::collections::map::HashMap<K, V, N: u32, B>)(self), hash, (#_cast returning u32)(attempt));
      let slot = (#_ref returning & std::collections::map::Slot<K, V>)((#_arrayIndex returning std::collections::map::Slot<K, V>)((#_readRef returning std::collections::map::HashMap<K, V, N: u32, B>)(self).0, (#_cast returning u32)(index)));
      let insert = (#_ref returning & bool)(#_false);
      if (std::collections::map::Slot::is_available<K, V> as λ(std::collections::map::Slot<K, V>) -> bool)((#_readRef returning std::collections::map::Slot<K, V>)(slot)) then {
        insert = #_true;
        ((*self: std::collections::map::HashMap<K, V, N: u32, B>).1: u32) = (#_uAdd returning u32)((#_readRef returning std::collections::map::HashMap<K, V, N: u32, B>)(self).1, (1: u32));
        #_skip
      } else {
        if ((K as std::cmp::Eq<>)::eq<> as λ(K, K) -> bool)((#_readRef returning std::collections::map::Slot<K, V>)(slot).0, key) then {
          insert = #_true;
          #_skip
        }
      };
      if (#_readRef returning bool)(insert) then {
        (std::collections::map::Slot::set<K, V> as λ(& std::collections::map::Slot<K, V>, K, V) -> Unit)(slot, key, value);
        (((*self: std::collections::map::HashMap<K, V, N: u32, B>).0: Array<std::collections::map::Slot<K, V>, N: u32>)[index]: std::collections::map::Slot<K, V>) = (#_readRef returning std::collections::map::Slot<K, V>)(slot);
        should_break = #_true;
        #_skip
      }
    }
  };
  #_skip
}

noir_def std::collections::map::HashMap::remove<K: Type, V: Type, N: u32, B: Type, B_as_BuildHasher_H: Type>(self: & std::collections::map::HashMap<K, V, N: u32, B>, key: K) -> Unit := {
  let hash = (std::collections::map::HashMap::hash<K, V, N: u32, B, B_as_BuildHasher_H> as λ(std::collections::map::HashMap<K, V, N: u32, B>, K) -> u32)((#_readRef returning std::collections::map::HashMap<K, V, N: u32, B>)(self), key);
  let should_break = (#_ref returning & bool)(#_false);
  for attempt in (0: u32) .. uConst!(N: u32) do {
    if (#_bNot returning bool)((#_readRef returning bool)(should_break)) then {
      let index = (std::collections::map::HashMap::quadratic_probe<K, V, N: u32, B> as λ(std::collections::map::HashMap<K, V, N: u32, B>, u32, u32) -> u32)((#_readRef returning std::collections::map::HashMap<K, V, N: u32, B>)(self), hash, (#_cast returning u32)(attempt));
      let slot = (#_ref returning & std::collections::map::Slot<K, V>)((#_arrayIndex returning std::collections::map::Slot<K, V>)((#_readRef returning std::collections::map::HashMap<K, V, N: u32, B>)(self).0, (#_cast returning u32)(index)));
      if (std::collections::map::Slot::is_valid<K, V> as λ(std::collections::map::Slot<K, V>) -> bool)((#_readRef returning std::collections::map::Slot<K, V>)(slot)) then {
        if ((K as std::cmp::Eq<>)::eq<> as λ(K, K) -> bool)((#_readRef returning std::collections::map::Slot<K, V>)(slot).0, key) then {
          (std::collections::map::Slot::mark_deleted<K, V> as λ(& std::collections::map::Slot<K, V>) -> Unit)(slot);
          (((*self: std::collections::map::HashMap<K, V, N: u32, B>).0: Array<std::collections::map::Slot<K, V>, N: u32>)[index]: std::collections::map::Slot<K, V>) = (#_readRef returning std::collections::map::Slot<K, V>)(slot);
          ((*self: std::collections::map::HashMap<K, V, N: u32, B>).1: u32) = (#_uSub returning u32)((#_readRef returning std::collections::map::HashMap<K, V, N: u32, B>)(self).1, (1: u32));
          should_break = #_true;
          #_skip
        }
      }
    }
  };
  #_skip
}

noir_def std::collections::map::HashMap::hash<K: Type, V: Type, N: u32, B: Type, B_as_BuildHasher_H: Type>(self: std::collections::map::HashMap<K, V, N: u32, B>, key: K) -> u32 := {
  let hasher = (#_ref returning & B_as_BuildHasher_H)(((B as std::hash::BuildHasher<>)::build_hasher<> as λ(B) -> B_as_BuildHasher_H)(self.2));
  ((K as std::hash::Hash<>)::hash<B_as_BuildHasher_H> as λ(K, & B_as_BuildHasher_H) -> Unit)(key, hasher);
  (#_cast returning u32)(((B_as_BuildHasher_H as std::hash::Hasher<>)::finish<> as λ(B_as_BuildHasher_H) -> Field)((#_readRef returning B_as_BuildHasher_H)(hasher)))
}

noir_def std::collections::map::HashMap::quadratic_probe<K: Type, V: Type, N: u32, B: Type>(_self: std::collections::map::HashMap<K, V, N: u32, B>, hash: u32, attempt: u32) -> u32 := {
  let attempt_u64 = (#_cast returning u64)(attempt);
  let offset = (#_uDiv returning u64)((#_uAdd returning u64)(attempt_u64, (#_uMul returning u64)(attempt_u64, attempt_u64)), (2: u64));
  (#_cast returning u32)((#_uRem returning u64)((#_uAdd returning u64)((#_cast returning u64)(hash), offset), (#_cast returning u64)(uConst!(N: u32))))
}

noir_def std::collections::map::HashMap::assert_load_factor<K: Type, V: Type, N: u32, B: Type>(self: std::collections::map::HashMap<K, V, N: u32, B>) -> Unit := {
  let lhs = (#_uMul returning u32)(self.1, (std::collections::map::MAX_LOAD_FACTOR_DENOMINATOR<> as λ() -> u32)());
  let rhs = (#_uMul returning u32)((#_arrayLen returning u32)(self.0), (std::collections::map::MAX_LOAD_FACTOR_NUMERATOR<> as λ() -> u32)());
  let exceeded = (#_uGeq returning bool)(lhs, rhs);
  (#_assert returning Unit)((#_bNot returning bool)(exceeded));
  #_skip
}

noir_trait_impl[std.impl_35]<K: Type, V: Type, N: u32, B: Type, B_as_BuildHasher_H: Type> std::cmp::Eq<> for std::collections::map::HashMap<K, V, N: u32, B> where [K: std::cmp::Eq<>, K: std::hash::Hash<>, V: std::cmp::Eq<>, B: std::hash::BuildHasher<B_as_BuildHasher_H>] := {
  noir_def eq<>(self: std::collections::map::HashMap<K, V, N: u32, B>, other: std::collections::map::HashMap<K, V, N: u32, B>) -> bool := {
    let equal = (#_ref returning & bool)(#_false);
    if (#_uEq returning bool)((std::collections::map::HashMap::len<K, V, N: u32, B> as λ(std::collections::map::HashMap<K, V, N: u32, B>) -> u32)(self), (std::collections::map::HashMap::len<K, V, N: u32, B> as λ(std::collections::map::HashMap<K, V, N: u32, B>) -> u32)(other)) then {
      equal = #_true;
      {
        let ζi0 = self.0;
        for ζi1 in (0: u32) .. (#_arrayLen returning u32)(ζi0) do {
          let slot = (#_arrayIndex returning std::collections::map::Slot<K, V>)(ζi0, (#_cast returning u32)(ζi1));
          {
            if (#_bAnd returning bool)((#_readRef returning bool)(equal), (std::collections::map::Slot::is_valid<K, V> as λ(std::collections::map::Slot<K, V>) -> bool)(slot)) then {
              let other_value = (std::collections::map::HashMap::get<K, V, N: u32, B, B_as_BuildHasher_H> as λ(std::collections::map::HashMap<K, V, N: u32, B>, K) -> std::option::Option<V>)(other, slot.0);
              if (std::option::Option::is_none<V> as λ(std::option::Option<V>) -> bool)(other_value) then {
                equal = #_false;
                #_skip
              } else {
                let other_value = (std::option::Option::unwrap_unchecked<V> as λ(std::option::Option<V>) -> V)(other_value);
                if (#_bNot returning bool)(((V as std::cmp::Eq<>)::eq<> as λ(V, V) -> bool)(slot.1, other_value)) then {
                  equal = #_false;
                  #_skip
                }
              }
            }
          }
        };
        #_skip
      }
    };
    (#_readRef returning bool)(equal)
  };
}

noir_trait_impl[std.impl_36]<K: Type, V: Type, N: u32, B: Type, B_as_BuildHasher_H: Type> std::default::Default<> for std::collections::map::HashMap<K, V, N: u32, B> where [B: std::hash::BuildHasher<B_as_BuildHasher_H>, B: std::default::Default<>] := {
  noir_def default<>() -> std::collections::map::HashMap<K, V, N: u32, B> := {
    let _build_hasher = ((B as std::default::Default<>)::default<> as λ() -> B)();
    let map = (std::collections::map::HashMap::with_hasher<K, V, N: u32, B, B_as_BuildHasher_H> as λ(B) -> std::collections::map::HashMap<K, V, N: u32, B>)(_build_hasher);
    map
  };
}

noir_def std::collections::map::test::test_quadratic_probe_function<>() -> Unit := {
  let map = ((std::collections::map::HashMap<Field, Field, 1000: u32, std::hash::BuildHasherDefault<std::hash::poseidon2::Poseidon2Hasher<> > > as std::default::Default<>)::default<> as λ() -> std::collections::map::HashMap<Field, Field, 1000: u32, std::hash::BuildHasherDefault<std::hash::poseidon2::Poseidon2Hasher<> > >)();
  let hash1 = (123: u32);
  let attempt1 = (1000000: u32);
  let result = (std::collections::map::HashMap::quadratic_probe<Field, 1000: u32, std::hash::BuildHasherDefault<std::hash::poseidon2::Poseidon2Hasher<> > > as λ(std::collections::map::HashMap<Field, Field, 1000: u32, std::hash::BuildHasherDefault<std::hash::poseidon2::Poseidon2Hasher<> > >, u32, u32) -> u32)(map, hash1, attempt1);
  (#_assert returning Unit)((#_uEq returning bool)(result, (123: u32)));
  #_skip
}

def std.Collections.Map.env : Env := Env.mk
  [«std::collections::map::MAX_LOAD_FACTOR_NUMERATOR», «std::collections::map::MAX_LOAD_FACTOR_DENOMINATOR», «std::collections::map::Slot::is_valid», «std::collections::map::Slot::is_available», «std::collections::map::Slot::set», «std::collections::map::Slot::mark_deleted», «std::collections::map::HashMap::with_hasher», «std::collections::map::HashMap::clear», «std::collections::map::HashMap::contains_key», «std::collections::map::HashMap::is_empty», «std::collections::map::HashMap::entries», «std::collections::map::HashMap::keys», «std::collections::map::HashMap::values», «std::collections::map::HashMap::iter_mut», «std::collections::map::HashMap::iter_keys_mut», «std::collections::map::HashMap::iter_values_mut», «std::collections::map::HashMap::retain», «std::collections::map::HashMap::len», «std::collections::map::HashMap::capacity», «std::collections::map::HashMap::get», «std::collections::map::HashMap::insert», «std::collections::map::HashMap::remove», «std::collections::map::HashMap::hash», «std::collections::map::HashMap::quadratic_probe», «std::collections::map::HashMap::assert_load_factor», «std::collections::map::test::test_quadratic_probe_function»]
  [std.impl_34, std.impl_35, std.impl_36]
