-- Generated by lampe

import std.Extracted.GeneratedTypes
import «hasher-0.0.0».Extracted.GeneratedTypes
import Lampe

open Lampe

set_option linter.unusedVariables false

noir_struct_def «skyscraper-0.0.0»::Skyscraper<> {}

