-- Generated by lampe

import «Merkle-0.0.0».Extracted.GeneratedTypes
import «Merkle-0.0.0».Extracted.Main
import «Merkle-0.0.0».Extracted.Witness.Mod
import «Merkle-0.0.0».Extracted.Witness.Uncons
import «hasher-0.0.0».Extracted
import «skyscraper-0.0.0».Extracted
import std.Extracted

namespace «Merkle-0.0.0»

def env := Main.env
  ++ Witness.Mod.env
  ++ Witness.Uncons.env
  ++ «hasher-0.0.0».env
  ++ «skyscraper-0.0.0».env
  ++ std.env
